
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BalanceTransaction` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model BalanceTransaction
 * 
 */
export type BalanceTransactionModel = runtime.Types.Result.DefaultSelection<Prisma.$BalanceTransactionPayload>

export type AggregateBalanceTransaction = {
  _count: BalanceTransactionCountAggregateOutputType | null
  _avg: BalanceTransactionAvgAggregateOutputType | null
  _sum: BalanceTransactionSumAggregateOutputType | null
  _min: BalanceTransactionMinAggregateOutputType | null
  _max: BalanceTransactionMaxAggregateOutputType | null
}

export type BalanceTransactionAvgAggregateOutputType = {
  amount: runtime.Decimal | null
}

export type BalanceTransactionSumAggregateOutputType = {
  amount: runtime.Decimal | null
}

export type BalanceTransactionMinAggregateOutputType = {
  id: string | null
  userId: string | null
  amount: runtime.Decimal | null
  status: $Enums.BalanceStatusEnums | null
  createdAt: Date | null
}

export type BalanceTransactionMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  amount: runtime.Decimal | null
  status: $Enums.BalanceStatusEnums | null
  createdAt: Date | null
}

export type BalanceTransactionCountAggregateOutputType = {
  id: number
  userId: number
  amount: number
  status: number
  meta: number
  createdAt: number
  _all: number
}


export type BalanceTransactionAvgAggregateInputType = {
  amount?: true
}

export type BalanceTransactionSumAggregateInputType = {
  amount?: true
}

export type BalanceTransactionMinAggregateInputType = {
  id?: true
  userId?: true
  amount?: true
  status?: true
  createdAt?: true
}

export type BalanceTransactionMaxAggregateInputType = {
  id?: true
  userId?: true
  amount?: true
  status?: true
  createdAt?: true
}

export type BalanceTransactionCountAggregateInputType = {
  id?: true
  userId?: true
  amount?: true
  status?: true
  meta?: true
  createdAt?: true
  _all?: true
}

export type BalanceTransactionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BalanceTransaction to aggregate.
   */
  where?: Prisma.BalanceTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BalanceTransactions to fetch.
   */
  orderBy?: Prisma.BalanceTransactionOrderByWithRelationInput | Prisma.BalanceTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BalanceTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BalanceTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BalanceTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BalanceTransactions
  **/
  _count?: true | BalanceTransactionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BalanceTransactionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BalanceTransactionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BalanceTransactionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BalanceTransactionMaxAggregateInputType
}

export type GetBalanceTransactionAggregateType<T extends BalanceTransactionAggregateArgs> = {
      [P in keyof T & keyof AggregateBalanceTransaction]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBalanceTransaction[P]>
    : Prisma.GetScalarType<T[P], AggregateBalanceTransaction[P]>
}




export type BalanceTransactionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BalanceTransactionWhereInput
  orderBy?: Prisma.BalanceTransactionOrderByWithAggregationInput | Prisma.BalanceTransactionOrderByWithAggregationInput[]
  by: Prisma.BalanceTransactionScalarFieldEnum[] | Prisma.BalanceTransactionScalarFieldEnum
  having?: Prisma.BalanceTransactionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BalanceTransactionCountAggregateInputType | true
  _avg?: BalanceTransactionAvgAggregateInputType
  _sum?: BalanceTransactionSumAggregateInputType
  _min?: BalanceTransactionMinAggregateInputType
  _max?: BalanceTransactionMaxAggregateInputType
}

export type BalanceTransactionGroupByOutputType = {
  id: string
  userId: string
  amount: runtime.Decimal
  status: $Enums.BalanceStatusEnums
  meta: runtime.JsonValue | null
  createdAt: Date
  _count: BalanceTransactionCountAggregateOutputType | null
  _avg: BalanceTransactionAvgAggregateOutputType | null
  _sum: BalanceTransactionSumAggregateOutputType | null
  _min: BalanceTransactionMinAggregateOutputType | null
  _max: BalanceTransactionMaxAggregateOutputType | null
}

type GetBalanceTransactionGroupByPayload<T extends BalanceTransactionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BalanceTransactionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BalanceTransactionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BalanceTransactionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BalanceTransactionGroupByOutputType[P]>
      }
    >
  >



export type BalanceTransactionWhereInput = {
  AND?: Prisma.BalanceTransactionWhereInput | Prisma.BalanceTransactionWhereInput[]
  OR?: Prisma.BalanceTransactionWhereInput[]
  NOT?: Prisma.BalanceTransactionWhereInput | Prisma.BalanceTransactionWhereInput[]
  id?: Prisma.StringFilter<"BalanceTransaction"> | string
  userId?: Prisma.StringFilter<"BalanceTransaction"> | string
  amount?: Prisma.DecimalFilter<"BalanceTransaction"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumBalanceStatusEnumsFilter<"BalanceTransaction"> | $Enums.BalanceStatusEnums
  meta?: Prisma.JsonNullableFilter<"BalanceTransaction">
  createdAt?: Prisma.DateTimeFilter<"BalanceTransaction"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type BalanceTransactionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  meta?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type BalanceTransactionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BalanceTransactionWhereInput | Prisma.BalanceTransactionWhereInput[]
  OR?: Prisma.BalanceTransactionWhereInput[]
  NOT?: Prisma.BalanceTransactionWhereInput | Prisma.BalanceTransactionWhereInput[]
  userId?: Prisma.StringFilter<"BalanceTransaction"> | string
  amount?: Prisma.DecimalFilter<"BalanceTransaction"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumBalanceStatusEnumsFilter<"BalanceTransaction"> | $Enums.BalanceStatusEnums
  meta?: Prisma.JsonNullableFilter<"BalanceTransaction">
  createdAt?: Prisma.DateTimeFilter<"BalanceTransaction"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type BalanceTransactionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  meta?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.BalanceTransactionCountOrderByAggregateInput
  _avg?: Prisma.BalanceTransactionAvgOrderByAggregateInput
  _max?: Prisma.BalanceTransactionMaxOrderByAggregateInput
  _min?: Prisma.BalanceTransactionMinOrderByAggregateInput
  _sum?: Prisma.BalanceTransactionSumOrderByAggregateInput
}

export type BalanceTransactionScalarWhereWithAggregatesInput = {
  AND?: Prisma.BalanceTransactionScalarWhereWithAggregatesInput | Prisma.BalanceTransactionScalarWhereWithAggregatesInput[]
  OR?: Prisma.BalanceTransactionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BalanceTransactionScalarWhereWithAggregatesInput | Prisma.BalanceTransactionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BalanceTransaction"> | string
  userId?: Prisma.StringWithAggregatesFilter<"BalanceTransaction"> | string
  amount?: Prisma.DecimalWithAggregatesFilter<"BalanceTransaction"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumBalanceStatusEnumsWithAggregatesFilter<"BalanceTransaction"> | $Enums.BalanceStatusEnums
  meta?: Prisma.JsonNullableWithAggregatesFilter<"BalanceTransaction">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BalanceTransaction"> | Date | string
}

export type BalanceTransactionCreateInput = {
  id?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  status: $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutBalanceTransactionsInput
}

export type BalanceTransactionUncheckedCreateInput = {
  id?: string
  userId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  status: $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type BalanceTransactionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumBalanceStatusEnumsFieldUpdateOperationsInput | $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutBalanceTransactionsNestedInput
}

export type BalanceTransactionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumBalanceStatusEnumsFieldUpdateOperationsInput | $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BalanceTransactionCreateManyInput = {
  id?: string
  userId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  status: $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type BalanceTransactionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumBalanceStatusEnumsFieldUpdateOperationsInput | $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BalanceTransactionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumBalanceStatusEnumsFieldUpdateOperationsInput | $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BalanceTransactionListRelationFilter = {
  every?: Prisma.BalanceTransactionWhereInput
  some?: Prisma.BalanceTransactionWhereInput
  none?: Prisma.BalanceTransactionWhereInput
}

export type BalanceTransactionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BalanceTransactionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  meta?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BalanceTransactionAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type BalanceTransactionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BalanceTransactionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BalanceTransactionSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type BalanceTransactionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BalanceTransactionCreateWithoutUserInput, Prisma.BalanceTransactionUncheckedCreateWithoutUserInput> | Prisma.BalanceTransactionCreateWithoutUserInput[] | Prisma.BalanceTransactionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BalanceTransactionCreateOrConnectWithoutUserInput | Prisma.BalanceTransactionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BalanceTransactionCreateManyUserInputEnvelope
  connect?: Prisma.BalanceTransactionWhereUniqueInput | Prisma.BalanceTransactionWhereUniqueInput[]
}

export type BalanceTransactionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BalanceTransactionCreateWithoutUserInput, Prisma.BalanceTransactionUncheckedCreateWithoutUserInput> | Prisma.BalanceTransactionCreateWithoutUserInput[] | Prisma.BalanceTransactionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BalanceTransactionCreateOrConnectWithoutUserInput | Prisma.BalanceTransactionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BalanceTransactionCreateManyUserInputEnvelope
  connect?: Prisma.BalanceTransactionWhereUniqueInput | Prisma.BalanceTransactionWhereUniqueInput[]
}

export type BalanceTransactionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BalanceTransactionCreateWithoutUserInput, Prisma.BalanceTransactionUncheckedCreateWithoutUserInput> | Prisma.BalanceTransactionCreateWithoutUserInput[] | Prisma.BalanceTransactionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BalanceTransactionCreateOrConnectWithoutUserInput | Prisma.BalanceTransactionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BalanceTransactionUpsertWithWhereUniqueWithoutUserInput | Prisma.BalanceTransactionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BalanceTransactionCreateManyUserInputEnvelope
  set?: Prisma.BalanceTransactionWhereUniqueInput | Prisma.BalanceTransactionWhereUniqueInput[]
  disconnect?: Prisma.BalanceTransactionWhereUniqueInput | Prisma.BalanceTransactionWhereUniqueInput[]
  delete?: Prisma.BalanceTransactionWhereUniqueInput | Prisma.BalanceTransactionWhereUniqueInput[]
  connect?: Prisma.BalanceTransactionWhereUniqueInput | Prisma.BalanceTransactionWhereUniqueInput[]
  update?: Prisma.BalanceTransactionUpdateWithWhereUniqueWithoutUserInput | Prisma.BalanceTransactionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BalanceTransactionUpdateManyWithWhereWithoutUserInput | Prisma.BalanceTransactionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BalanceTransactionScalarWhereInput | Prisma.BalanceTransactionScalarWhereInput[]
}

export type BalanceTransactionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BalanceTransactionCreateWithoutUserInput, Prisma.BalanceTransactionUncheckedCreateWithoutUserInput> | Prisma.BalanceTransactionCreateWithoutUserInput[] | Prisma.BalanceTransactionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BalanceTransactionCreateOrConnectWithoutUserInput | Prisma.BalanceTransactionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BalanceTransactionUpsertWithWhereUniqueWithoutUserInput | Prisma.BalanceTransactionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BalanceTransactionCreateManyUserInputEnvelope
  set?: Prisma.BalanceTransactionWhereUniqueInput | Prisma.BalanceTransactionWhereUniqueInput[]
  disconnect?: Prisma.BalanceTransactionWhereUniqueInput | Prisma.BalanceTransactionWhereUniqueInput[]
  delete?: Prisma.BalanceTransactionWhereUniqueInput | Prisma.BalanceTransactionWhereUniqueInput[]
  connect?: Prisma.BalanceTransactionWhereUniqueInput | Prisma.BalanceTransactionWhereUniqueInput[]
  update?: Prisma.BalanceTransactionUpdateWithWhereUniqueWithoutUserInput | Prisma.BalanceTransactionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BalanceTransactionUpdateManyWithWhereWithoutUserInput | Prisma.BalanceTransactionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BalanceTransactionScalarWhereInput | Prisma.BalanceTransactionScalarWhereInput[]
}

export type EnumBalanceStatusEnumsFieldUpdateOperationsInput = {
  set?: $Enums.BalanceStatusEnums
}

export type BalanceTransactionCreateWithoutUserInput = {
  id?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  status: $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type BalanceTransactionUncheckedCreateWithoutUserInput = {
  id?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  status: $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type BalanceTransactionCreateOrConnectWithoutUserInput = {
  where: Prisma.BalanceTransactionWhereUniqueInput
  create: Prisma.XOR<Prisma.BalanceTransactionCreateWithoutUserInput, Prisma.BalanceTransactionUncheckedCreateWithoutUserInput>
}

export type BalanceTransactionCreateManyUserInputEnvelope = {
  data: Prisma.BalanceTransactionCreateManyUserInput | Prisma.BalanceTransactionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type BalanceTransactionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.BalanceTransactionWhereUniqueInput
  update: Prisma.XOR<Prisma.BalanceTransactionUpdateWithoutUserInput, Prisma.BalanceTransactionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.BalanceTransactionCreateWithoutUserInput, Prisma.BalanceTransactionUncheckedCreateWithoutUserInput>
}

export type BalanceTransactionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.BalanceTransactionWhereUniqueInput
  data: Prisma.XOR<Prisma.BalanceTransactionUpdateWithoutUserInput, Prisma.BalanceTransactionUncheckedUpdateWithoutUserInput>
}

export type BalanceTransactionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.BalanceTransactionScalarWhereInput
  data: Prisma.XOR<Prisma.BalanceTransactionUpdateManyMutationInput, Prisma.BalanceTransactionUncheckedUpdateManyWithoutUserInput>
}

export type BalanceTransactionScalarWhereInput = {
  AND?: Prisma.BalanceTransactionScalarWhereInput | Prisma.BalanceTransactionScalarWhereInput[]
  OR?: Prisma.BalanceTransactionScalarWhereInput[]
  NOT?: Prisma.BalanceTransactionScalarWhereInput | Prisma.BalanceTransactionScalarWhereInput[]
  id?: Prisma.StringFilter<"BalanceTransaction"> | string
  userId?: Prisma.StringFilter<"BalanceTransaction"> | string
  amount?: Prisma.DecimalFilter<"BalanceTransaction"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumBalanceStatusEnumsFilter<"BalanceTransaction"> | $Enums.BalanceStatusEnums
  meta?: Prisma.JsonNullableFilter<"BalanceTransaction">
  createdAt?: Prisma.DateTimeFilter<"BalanceTransaction"> | Date | string
}

export type BalanceTransactionCreateManyUserInput = {
  id?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  status: $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type BalanceTransactionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumBalanceStatusEnumsFieldUpdateOperationsInput | $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BalanceTransactionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumBalanceStatusEnumsFieldUpdateOperationsInput | $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BalanceTransactionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumBalanceStatusEnumsFieldUpdateOperationsInput | $Enums.BalanceStatusEnums
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type BalanceTransactionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  amount?: boolean
  status?: boolean
  meta?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["balanceTransaction"]>

export type BalanceTransactionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  amount?: boolean
  status?: boolean
  meta?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["balanceTransaction"]>

export type BalanceTransactionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  amount?: boolean
  status?: boolean
  meta?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["balanceTransaction"]>

export type BalanceTransactionSelectScalar = {
  id?: boolean
  userId?: boolean
  amount?: boolean
  status?: boolean
  meta?: boolean
  createdAt?: boolean
}

export type BalanceTransactionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "amount" | "status" | "meta" | "createdAt", ExtArgs["result"]["balanceTransaction"]>
export type BalanceTransactionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BalanceTransactionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BalanceTransactionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $BalanceTransactionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BalanceTransaction"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    amount: runtime.Decimal
    status: $Enums.BalanceStatusEnums
    meta: runtime.JsonValue | null
    createdAt: Date
  }, ExtArgs["result"]["balanceTransaction"]>
  composites: {}
}

export type BalanceTransactionGetPayload<S extends boolean | null | undefined | BalanceTransactionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BalanceTransactionPayload, S>

export type BalanceTransactionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BalanceTransactionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BalanceTransactionCountAggregateInputType | true
  }

export interface BalanceTransactionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BalanceTransaction'], meta: { name: 'BalanceTransaction' } }
  /**
   * Find zero or one BalanceTransaction that matches the filter.
   * @param {BalanceTransactionFindUniqueArgs} args - Arguments to find a BalanceTransaction
   * @example
   * // Get one BalanceTransaction
   * const balanceTransaction = await prisma.balanceTransaction.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BalanceTransactionFindUniqueArgs>(args: Prisma.SelectSubset<T, BalanceTransactionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BalanceTransactionClient<runtime.Types.Result.GetResult<Prisma.$BalanceTransactionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BalanceTransaction that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BalanceTransactionFindUniqueOrThrowArgs} args - Arguments to find a BalanceTransaction
   * @example
   * // Get one BalanceTransaction
   * const balanceTransaction = await prisma.balanceTransaction.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BalanceTransactionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BalanceTransactionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BalanceTransactionClient<runtime.Types.Result.GetResult<Prisma.$BalanceTransactionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BalanceTransaction that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BalanceTransactionFindFirstArgs} args - Arguments to find a BalanceTransaction
   * @example
   * // Get one BalanceTransaction
   * const balanceTransaction = await prisma.balanceTransaction.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BalanceTransactionFindFirstArgs>(args?: Prisma.SelectSubset<T, BalanceTransactionFindFirstArgs<ExtArgs>>): Prisma.Prisma__BalanceTransactionClient<runtime.Types.Result.GetResult<Prisma.$BalanceTransactionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BalanceTransaction that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BalanceTransactionFindFirstOrThrowArgs} args - Arguments to find a BalanceTransaction
   * @example
   * // Get one BalanceTransaction
   * const balanceTransaction = await prisma.balanceTransaction.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BalanceTransactionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BalanceTransactionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BalanceTransactionClient<runtime.Types.Result.GetResult<Prisma.$BalanceTransactionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BalanceTransactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BalanceTransactionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BalanceTransactions
   * const balanceTransactions = await prisma.balanceTransaction.findMany()
   * 
   * // Get first 10 BalanceTransactions
   * const balanceTransactions = await prisma.balanceTransaction.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const balanceTransactionWithIdOnly = await prisma.balanceTransaction.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BalanceTransactionFindManyArgs>(args?: Prisma.SelectSubset<T, BalanceTransactionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BalanceTransactionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BalanceTransaction.
   * @param {BalanceTransactionCreateArgs} args - Arguments to create a BalanceTransaction.
   * @example
   * // Create one BalanceTransaction
   * const BalanceTransaction = await prisma.balanceTransaction.create({
   *   data: {
   *     // ... data to create a BalanceTransaction
   *   }
   * })
   * 
   */
  create<T extends BalanceTransactionCreateArgs>(args: Prisma.SelectSubset<T, BalanceTransactionCreateArgs<ExtArgs>>): Prisma.Prisma__BalanceTransactionClient<runtime.Types.Result.GetResult<Prisma.$BalanceTransactionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BalanceTransactions.
   * @param {BalanceTransactionCreateManyArgs} args - Arguments to create many BalanceTransactions.
   * @example
   * // Create many BalanceTransactions
   * const balanceTransaction = await prisma.balanceTransaction.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BalanceTransactionCreateManyArgs>(args?: Prisma.SelectSubset<T, BalanceTransactionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BalanceTransactions and returns the data saved in the database.
   * @param {BalanceTransactionCreateManyAndReturnArgs} args - Arguments to create many BalanceTransactions.
   * @example
   * // Create many BalanceTransactions
   * const balanceTransaction = await prisma.balanceTransaction.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BalanceTransactions and only return the `id`
   * const balanceTransactionWithIdOnly = await prisma.balanceTransaction.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BalanceTransactionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BalanceTransactionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BalanceTransactionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BalanceTransaction.
   * @param {BalanceTransactionDeleteArgs} args - Arguments to delete one BalanceTransaction.
   * @example
   * // Delete one BalanceTransaction
   * const BalanceTransaction = await prisma.balanceTransaction.delete({
   *   where: {
   *     // ... filter to delete one BalanceTransaction
   *   }
   * })
   * 
   */
  delete<T extends BalanceTransactionDeleteArgs>(args: Prisma.SelectSubset<T, BalanceTransactionDeleteArgs<ExtArgs>>): Prisma.Prisma__BalanceTransactionClient<runtime.Types.Result.GetResult<Prisma.$BalanceTransactionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BalanceTransaction.
   * @param {BalanceTransactionUpdateArgs} args - Arguments to update one BalanceTransaction.
   * @example
   * // Update one BalanceTransaction
   * const balanceTransaction = await prisma.balanceTransaction.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BalanceTransactionUpdateArgs>(args: Prisma.SelectSubset<T, BalanceTransactionUpdateArgs<ExtArgs>>): Prisma.Prisma__BalanceTransactionClient<runtime.Types.Result.GetResult<Prisma.$BalanceTransactionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BalanceTransactions.
   * @param {BalanceTransactionDeleteManyArgs} args - Arguments to filter BalanceTransactions to delete.
   * @example
   * // Delete a few BalanceTransactions
   * const { count } = await prisma.balanceTransaction.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BalanceTransactionDeleteManyArgs>(args?: Prisma.SelectSubset<T, BalanceTransactionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BalanceTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BalanceTransactionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BalanceTransactions
   * const balanceTransaction = await prisma.balanceTransaction.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BalanceTransactionUpdateManyArgs>(args: Prisma.SelectSubset<T, BalanceTransactionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BalanceTransactions and returns the data updated in the database.
   * @param {BalanceTransactionUpdateManyAndReturnArgs} args - Arguments to update many BalanceTransactions.
   * @example
   * // Update many BalanceTransactions
   * const balanceTransaction = await prisma.balanceTransaction.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BalanceTransactions and only return the `id`
   * const balanceTransactionWithIdOnly = await prisma.balanceTransaction.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BalanceTransactionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BalanceTransactionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BalanceTransactionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BalanceTransaction.
   * @param {BalanceTransactionUpsertArgs} args - Arguments to update or create a BalanceTransaction.
   * @example
   * // Update or create a BalanceTransaction
   * const balanceTransaction = await prisma.balanceTransaction.upsert({
   *   create: {
   *     // ... data to create a BalanceTransaction
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BalanceTransaction we want to update
   *   }
   * })
   */
  upsert<T extends BalanceTransactionUpsertArgs>(args: Prisma.SelectSubset<T, BalanceTransactionUpsertArgs<ExtArgs>>): Prisma.Prisma__BalanceTransactionClient<runtime.Types.Result.GetResult<Prisma.$BalanceTransactionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BalanceTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BalanceTransactionCountArgs} args - Arguments to filter BalanceTransactions to count.
   * @example
   * // Count the number of BalanceTransactions
   * const count = await prisma.balanceTransaction.count({
   *   where: {
   *     // ... the filter for the BalanceTransactions we want to count
   *   }
   * })
  **/
  count<T extends BalanceTransactionCountArgs>(
    args?: Prisma.Subset<T, BalanceTransactionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BalanceTransactionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BalanceTransaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BalanceTransactionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BalanceTransactionAggregateArgs>(args: Prisma.Subset<T, BalanceTransactionAggregateArgs>): Prisma.PrismaPromise<GetBalanceTransactionAggregateType<T>>

  /**
   * Group by BalanceTransaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BalanceTransactionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BalanceTransactionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BalanceTransactionGroupByArgs['orderBy'] }
      : { orderBy?: BalanceTransactionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BalanceTransactionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBalanceTransactionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BalanceTransaction model
 */
readonly fields: BalanceTransactionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BalanceTransaction.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BalanceTransactionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BalanceTransaction model
 */
export interface BalanceTransactionFieldRefs {
  readonly id: Prisma.FieldRef<"BalanceTransaction", 'String'>
  readonly userId: Prisma.FieldRef<"BalanceTransaction", 'String'>
  readonly amount: Prisma.FieldRef<"BalanceTransaction", 'Decimal'>
  readonly status: Prisma.FieldRef<"BalanceTransaction", 'BalanceStatusEnums'>
  readonly meta: Prisma.FieldRef<"BalanceTransaction", 'Json'>
  readonly createdAt: Prisma.FieldRef<"BalanceTransaction", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BalanceTransaction findUnique
 */
export type BalanceTransactionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BalanceTransaction
   */
  select?: Prisma.BalanceTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BalanceTransaction
   */
  omit?: Prisma.BalanceTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceTransactionInclude<ExtArgs> | null
  /**
   * Filter, which BalanceTransaction to fetch.
   */
  where: Prisma.BalanceTransactionWhereUniqueInput
}

/**
 * BalanceTransaction findUniqueOrThrow
 */
export type BalanceTransactionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BalanceTransaction
   */
  select?: Prisma.BalanceTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BalanceTransaction
   */
  omit?: Prisma.BalanceTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceTransactionInclude<ExtArgs> | null
  /**
   * Filter, which BalanceTransaction to fetch.
   */
  where: Prisma.BalanceTransactionWhereUniqueInput
}

/**
 * BalanceTransaction findFirst
 */
export type BalanceTransactionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BalanceTransaction
   */
  select?: Prisma.BalanceTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BalanceTransaction
   */
  omit?: Prisma.BalanceTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceTransactionInclude<ExtArgs> | null
  /**
   * Filter, which BalanceTransaction to fetch.
   */
  where?: Prisma.BalanceTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BalanceTransactions to fetch.
   */
  orderBy?: Prisma.BalanceTransactionOrderByWithRelationInput | Prisma.BalanceTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BalanceTransactions.
   */
  cursor?: Prisma.BalanceTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BalanceTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BalanceTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BalanceTransactions.
   */
  distinct?: Prisma.BalanceTransactionScalarFieldEnum | Prisma.BalanceTransactionScalarFieldEnum[]
}

/**
 * BalanceTransaction findFirstOrThrow
 */
export type BalanceTransactionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BalanceTransaction
   */
  select?: Prisma.BalanceTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BalanceTransaction
   */
  omit?: Prisma.BalanceTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceTransactionInclude<ExtArgs> | null
  /**
   * Filter, which BalanceTransaction to fetch.
   */
  where?: Prisma.BalanceTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BalanceTransactions to fetch.
   */
  orderBy?: Prisma.BalanceTransactionOrderByWithRelationInput | Prisma.BalanceTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BalanceTransactions.
   */
  cursor?: Prisma.BalanceTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BalanceTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BalanceTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BalanceTransactions.
   */
  distinct?: Prisma.BalanceTransactionScalarFieldEnum | Prisma.BalanceTransactionScalarFieldEnum[]
}

/**
 * BalanceTransaction findMany
 */
export type BalanceTransactionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BalanceTransaction
   */
  select?: Prisma.BalanceTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BalanceTransaction
   */
  omit?: Prisma.BalanceTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceTransactionInclude<ExtArgs> | null
  /**
   * Filter, which BalanceTransactions to fetch.
   */
  where?: Prisma.BalanceTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BalanceTransactions to fetch.
   */
  orderBy?: Prisma.BalanceTransactionOrderByWithRelationInput | Prisma.BalanceTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BalanceTransactions.
   */
  cursor?: Prisma.BalanceTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BalanceTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BalanceTransactions.
   */
  skip?: number
  distinct?: Prisma.BalanceTransactionScalarFieldEnum | Prisma.BalanceTransactionScalarFieldEnum[]
}

/**
 * BalanceTransaction create
 */
export type BalanceTransactionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BalanceTransaction
   */
  select?: Prisma.BalanceTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BalanceTransaction
   */
  omit?: Prisma.BalanceTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceTransactionInclude<ExtArgs> | null
  /**
   * The data needed to create a BalanceTransaction.
   */
  data: Prisma.XOR<Prisma.BalanceTransactionCreateInput, Prisma.BalanceTransactionUncheckedCreateInput>
}

/**
 * BalanceTransaction createMany
 */
export type BalanceTransactionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BalanceTransactions.
   */
  data: Prisma.BalanceTransactionCreateManyInput | Prisma.BalanceTransactionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BalanceTransaction createManyAndReturn
 */
export type BalanceTransactionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BalanceTransaction
   */
  select?: Prisma.BalanceTransactionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BalanceTransaction
   */
  omit?: Prisma.BalanceTransactionOmit<ExtArgs> | null
  /**
   * The data used to create many BalanceTransactions.
   */
  data: Prisma.BalanceTransactionCreateManyInput | Prisma.BalanceTransactionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceTransactionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BalanceTransaction update
 */
export type BalanceTransactionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BalanceTransaction
   */
  select?: Prisma.BalanceTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BalanceTransaction
   */
  omit?: Prisma.BalanceTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceTransactionInclude<ExtArgs> | null
  /**
   * The data needed to update a BalanceTransaction.
   */
  data: Prisma.XOR<Prisma.BalanceTransactionUpdateInput, Prisma.BalanceTransactionUncheckedUpdateInput>
  /**
   * Choose, which BalanceTransaction to update.
   */
  where: Prisma.BalanceTransactionWhereUniqueInput
}

/**
 * BalanceTransaction updateMany
 */
export type BalanceTransactionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BalanceTransactions.
   */
  data: Prisma.XOR<Prisma.BalanceTransactionUpdateManyMutationInput, Prisma.BalanceTransactionUncheckedUpdateManyInput>
  /**
   * Filter which BalanceTransactions to update
   */
  where?: Prisma.BalanceTransactionWhereInput
  /**
   * Limit how many BalanceTransactions to update.
   */
  limit?: number
}

/**
 * BalanceTransaction updateManyAndReturn
 */
export type BalanceTransactionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BalanceTransaction
   */
  select?: Prisma.BalanceTransactionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BalanceTransaction
   */
  omit?: Prisma.BalanceTransactionOmit<ExtArgs> | null
  /**
   * The data used to update BalanceTransactions.
   */
  data: Prisma.XOR<Prisma.BalanceTransactionUpdateManyMutationInput, Prisma.BalanceTransactionUncheckedUpdateManyInput>
  /**
   * Filter which BalanceTransactions to update
   */
  where?: Prisma.BalanceTransactionWhereInput
  /**
   * Limit how many BalanceTransactions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceTransactionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BalanceTransaction upsert
 */
export type BalanceTransactionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BalanceTransaction
   */
  select?: Prisma.BalanceTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BalanceTransaction
   */
  omit?: Prisma.BalanceTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceTransactionInclude<ExtArgs> | null
  /**
   * The filter to search for the BalanceTransaction to update in case it exists.
   */
  where: Prisma.BalanceTransactionWhereUniqueInput
  /**
   * In case the BalanceTransaction found by the `where` argument doesn't exist, create a new BalanceTransaction with this data.
   */
  create: Prisma.XOR<Prisma.BalanceTransactionCreateInput, Prisma.BalanceTransactionUncheckedCreateInput>
  /**
   * In case the BalanceTransaction was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BalanceTransactionUpdateInput, Prisma.BalanceTransactionUncheckedUpdateInput>
}

/**
 * BalanceTransaction delete
 */
export type BalanceTransactionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BalanceTransaction
   */
  select?: Prisma.BalanceTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BalanceTransaction
   */
  omit?: Prisma.BalanceTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceTransactionInclude<ExtArgs> | null
  /**
   * Filter which BalanceTransaction to delete.
   */
  where: Prisma.BalanceTransactionWhereUniqueInput
}

/**
 * BalanceTransaction deleteMany
 */
export type BalanceTransactionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BalanceTransactions to delete
   */
  where?: Prisma.BalanceTransactionWhereInput
  /**
   * Limit how many BalanceTransactions to delete.
   */
  limit?: number
}

/**
 * BalanceTransaction without action
 */
export type BalanceTransactionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BalanceTransaction
   */
  select?: Prisma.BalanceTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BalanceTransaction
   */
  omit?: Prisma.BalanceTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceTransactionInclude<ExtArgs> | null
}
