
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BatchCheck` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model BatchCheck
 * 
 */
export type BatchCheckModel = runtime.Types.Result.DefaultSelection<Prisma.$BatchCheckPayload>

export type AggregateBatchCheck = {
  _count: BatchCheckCountAggregateOutputType | null
  _avg: BatchCheckAvgAggregateOutputType | null
  _sum: BatchCheckSumAggregateOutputType | null
  _min: BatchCheckMinAggregateOutputType | null
  _max: BatchCheckMaxAggregateOutputType | null
}

export type BatchCheckAvgAggregateOutputType = {
  totalItems: number | null
  successfulItems: number | null
  failedItems: number | null
  cost: number | null
  currentChunk: number | null
}

export type BatchCheckSumAggregateOutputType = {
  totalItems: number | null
  successfulItems: number | null
  failedItems: number | null
  cost: number | null
  currentChunk: number | null
}

export type BatchCheckMinAggregateOutputType = {
  id: string | null
  userId: string | null
  module: $Enums.CheckModuleEnums | null
  status: $Enums.CheckStatusEnums | null
  totalItems: number | null
  successfulItems: number | null
  failedItems: number | null
  cost: number | null
  currentChunk: number | null
  reportPath: string | null
  createdAt: Date | null
  updatedAt: Date | null
  completedAt: Date | null
}

export type BatchCheckMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  module: $Enums.CheckModuleEnums | null
  status: $Enums.CheckStatusEnums | null
  totalItems: number | null
  successfulItems: number | null
  failedItems: number | null
  cost: number | null
  currentChunk: number | null
  reportPath: string | null
  createdAt: Date | null
  updatedAt: Date | null
  completedAt: Date | null
}

export type BatchCheckCountAggregateOutputType = {
  id: number
  userId: number
  module: number
  status: number
  totalItems: number
  successfulItems: number
  failedItems: number
  cost: number
  currentChunk: number
  reportPath: number
  createdAt: number
  updatedAt: number
  completedAt: number
  _all: number
}


export type BatchCheckAvgAggregateInputType = {
  totalItems?: true
  successfulItems?: true
  failedItems?: true
  cost?: true
  currentChunk?: true
}

export type BatchCheckSumAggregateInputType = {
  totalItems?: true
  successfulItems?: true
  failedItems?: true
  cost?: true
  currentChunk?: true
}

export type BatchCheckMinAggregateInputType = {
  id?: true
  userId?: true
  module?: true
  status?: true
  totalItems?: true
  successfulItems?: true
  failedItems?: true
  cost?: true
  currentChunk?: true
  reportPath?: true
  createdAt?: true
  updatedAt?: true
  completedAt?: true
}

export type BatchCheckMaxAggregateInputType = {
  id?: true
  userId?: true
  module?: true
  status?: true
  totalItems?: true
  successfulItems?: true
  failedItems?: true
  cost?: true
  currentChunk?: true
  reportPath?: true
  createdAt?: true
  updatedAt?: true
  completedAt?: true
}

export type BatchCheckCountAggregateInputType = {
  id?: true
  userId?: true
  module?: true
  status?: true
  totalItems?: true
  successfulItems?: true
  failedItems?: true
  cost?: true
  currentChunk?: true
  reportPath?: true
  createdAt?: true
  updatedAt?: true
  completedAt?: true
  _all?: true
}

export type BatchCheckAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BatchCheck to aggregate.
   */
  where?: Prisma.BatchCheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BatchChecks to fetch.
   */
  orderBy?: Prisma.BatchCheckOrderByWithRelationInput | Prisma.BatchCheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BatchCheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BatchChecks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BatchChecks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BatchChecks
  **/
  _count?: true | BatchCheckCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BatchCheckAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BatchCheckSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BatchCheckMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BatchCheckMaxAggregateInputType
}

export type GetBatchCheckAggregateType<T extends BatchCheckAggregateArgs> = {
      [P in keyof T & keyof AggregateBatchCheck]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBatchCheck[P]>
    : Prisma.GetScalarType<T[P], AggregateBatchCheck[P]>
}




export type BatchCheckGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BatchCheckWhereInput
  orderBy?: Prisma.BatchCheckOrderByWithAggregationInput | Prisma.BatchCheckOrderByWithAggregationInput[]
  by: Prisma.BatchCheckScalarFieldEnum[] | Prisma.BatchCheckScalarFieldEnum
  having?: Prisma.BatchCheckScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BatchCheckCountAggregateInputType | true
  _avg?: BatchCheckAvgAggregateInputType
  _sum?: BatchCheckSumAggregateInputType
  _min?: BatchCheckMinAggregateInputType
  _max?: BatchCheckMaxAggregateInputType
}

export type BatchCheckGroupByOutputType = {
  id: string
  userId: string
  module: $Enums.CheckModuleEnums
  status: $Enums.CheckStatusEnums
  totalItems: number
  successfulItems: number
  failedItems: number
  cost: number
  currentChunk: number
  reportPath: string | null
  createdAt: Date
  updatedAt: Date
  completedAt: Date | null
  _count: BatchCheckCountAggregateOutputType | null
  _avg: BatchCheckAvgAggregateOutputType | null
  _sum: BatchCheckSumAggregateOutputType | null
  _min: BatchCheckMinAggregateOutputType | null
  _max: BatchCheckMaxAggregateOutputType | null
}

type GetBatchCheckGroupByPayload<T extends BatchCheckGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BatchCheckGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BatchCheckGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BatchCheckGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BatchCheckGroupByOutputType[P]>
      }
    >
  >



export type BatchCheckWhereInput = {
  AND?: Prisma.BatchCheckWhereInput | Prisma.BatchCheckWhereInput[]
  OR?: Prisma.BatchCheckWhereInput[]
  NOT?: Prisma.BatchCheckWhereInput | Prisma.BatchCheckWhereInput[]
  id?: Prisma.StringFilter<"BatchCheck"> | string
  userId?: Prisma.StringFilter<"BatchCheck"> | string
  module?: Prisma.EnumCheckModuleEnumsFilter<"BatchCheck"> | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFilter<"BatchCheck"> | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntFilter<"BatchCheck"> | number
  successfulItems?: Prisma.IntFilter<"BatchCheck"> | number
  failedItems?: Prisma.IntFilter<"BatchCheck"> | number
  cost?: Prisma.IntFilter<"BatchCheck"> | number
  currentChunk?: Prisma.IntFilter<"BatchCheck"> | number
  reportPath?: Prisma.StringNullableFilter<"BatchCheck"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BatchCheck"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BatchCheck"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"BatchCheck"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  checks?: Prisma.CheckListRelationFilter
}

export type BatchCheckOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  module?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalItems?: Prisma.SortOrder
  successfulItems?: Prisma.SortOrder
  failedItems?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  currentChunk?: Prisma.SortOrder
  reportPath?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  checks?: Prisma.CheckOrderByRelationAggregateInput
}

export type BatchCheckWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BatchCheckWhereInput | Prisma.BatchCheckWhereInput[]
  OR?: Prisma.BatchCheckWhereInput[]
  NOT?: Prisma.BatchCheckWhereInput | Prisma.BatchCheckWhereInput[]
  userId?: Prisma.StringFilter<"BatchCheck"> | string
  module?: Prisma.EnumCheckModuleEnumsFilter<"BatchCheck"> | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFilter<"BatchCheck"> | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntFilter<"BatchCheck"> | number
  successfulItems?: Prisma.IntFilter<"BatchCheck"> | number
  failedItems?: Prisma.IntFilter<"BatchCheck"> | number
  cost?: Prisma.IntFilter<"BatchCheck"> | number
  currentChunk?: Prisma.IntFilter<"BatchCheck"> | number
  reportPath?: Prisma.StringNullableFilter<"BatchCheck"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BatchCheck"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BatchCheck"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"BatchCheck"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  checks?: Prisma.CheckListRelationFilter
}, "id">

export type BatchCheckOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  module?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalItems?: Prisma.SortOrder
  successfulItems?: Prisma.SortOrder
  failedItems?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  currentChunk?: Prisma.SortOrder
  reportPath?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.BatchCheckCountOrderByAggregateInput
  _avg?: Prisma.BatchCheckAvgOrderByAggregateInput
  _max?: Prisma.BatchCheckMaxOrderByAggregateInput
  _min?: Prisma.BatchCheckMinOrderByAggregateInput
  _sum?: Prisma.BatchCheckSumOrderByAggregateInput
}

export type BatchCheckScalarWhereWithAggregatesInput = {
  AND?: Prisma.BatchCheckScalarWhereWithAggregatesInput | Prisma.BatchCheckScalarWhereWithAggregatesInput[]
  OR?: Prisma.BatchCheckScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BatchCheckScalarWhereWithAggregatesInput | Prisma.BatchCheckScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BatchCheck"> | string
  userId?: Prisma.StringWithAggregatesFilter<"BatchCheck"> | string
  module?: Prisma.EnumCheckModuleEnumsWithAggregatesFilter<"BatchCheck"> | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsWithAggregatesFilter<"BatchCheck"> | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntWithAggregatesFilter<"BatchCheck"> | number
  successfulItems?: Prisma.IntWithAggregatesFilter<"BatchCheck"> | number
  failedItems?: Prisma.IntWithAggregatesFilter<"BatchCheck"> | number
  cost?: Prisma.IntWithAggregatesFilter<"BatchCheck"> | number
  currentChunk?: Prisma.IntWithAggregatesFilter<"BatchCheck"> | number
  reportPath?: Prisma.StringNullableWithAggregatesFilter<"BatchCheck"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BatchCheck"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BatchCheck"> | Date | string
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"BatchCheck"> | Date | string | null
}

export type BatchCheckCreateInput = {
  id?: string
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  totalItems: number
  successfulItems?: number
  failedItems?: number
  cost: number
  currentChunk?: number
  reportPath?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutBatchesInput
  checks?: Prisma.CheckCreateNestedManyWithoutBatchInput
}

export type BatchCheckUncheckedCreateInput = {
  id?: string
  userId: string
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  totalItems: number
  successfulItems?: number
  failedItems?: number
  cost: number
  currentChunk?: number
  reportPath?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  checks?: Prisma.CheckUncheckedCreateNestedManyWithoutBatchInput
}

export type BatchCheckUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntFieldUpdateOperationsInput | number
  successfulItems?: Prisma.IntFieldUpdateOperationsInput | number
  failedItems?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  currentChunk?: Prisma.IntFieldUpdateOperationsInput | number
  reportPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutBatchesNestedInput
  checks?: Prisma.CheckUpdateManyWithoutBatchNestedInput
}

export type BatchCheckUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntFieldUpdateOperationsInput | number
  successfulItems?: Prisma.IntFieldUpdateOperationsInput | number
  failedItems?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  currentChunk?: Prisma.IntFieldUpdateOperationsInput | number
  reportPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  checks?: Prisma.CheckUncheckedUpdateManyWithoutBatchNestedInput
}

export type BatchCheckCreateManyInput = {
  id?: string
  userId: string
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  totalItems: number
  successfulItems?: number
  failedItems?: number
  cost: number
  currentChunk?: number
  reportPath?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
}

export type BatchCheckUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntFieldUpdateOperationsInput | number
  successfulItems?: Prisma.IntFieldUpdateOperationsInput | number
  failedItems?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  currentChunk?: Prisma.IntFieldUpdateOperationsInput | number
  reportPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BatchCheckUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntFieldUpdateOperationsInput | number
  successfulItems?: Prisma.IntFieldUpdateOperationsInput | number
  failedItems?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  currentChunk?: Prisma.IntFieldUpdateOperationsInput | number
  reportPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BatchCheckListRelationFilter = {
  every?: Prisma.BatchCheckWhereInput
  some?: Prisma.BatchCheckWhereInput
  none?: Prisma.BatchCheckWhereInput
}

export type BatchCheckOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BatchCheckNullableScalarRelationFilter = {
  is?: Prisma.BatchCheckWhereInput | null
  isNot?: Prisma.BatchCheckWhereInput | null
}

export type BatchCheckCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  module?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalItems?: Prisma.SortOrder
  successfulItems?: Prisma.SortOrder
  failedItems?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  currentChunk?: Prisma.SortOrder
  reportPath?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type BatchCheckAvgOrderByAggregateInput = {
  totalItems?: Prisma.SortOrder
  successfulItems?: Prisma.SortOrder
  failedItems?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  currentChunk?: Prisma.SortOrder
}

export type BatchCheckMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  module?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalItems?: Prisma.SortOrder
  successfulItems?: Prisma.SortOrder
  failedItems?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  currentChunk?: Prisma.SortOrder
  reportPath?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type BatchCheckMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  module?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalItems?: Prisma.SortOrder
  successfulItems?: Prisma.SortOrder
  failedItems?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  currentChunk?: Prisma.SortOrder
  reportPath?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type BatchCheckSumOrderByAggregateInput = {
  totalItems?: Prisma.SortOrder
  successfulItems?: Prisma.SortOrder
  failedItems?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  currentChunk?: Prisma.SortOrder
}

export type BatchCheckCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BatchCheckCreateWithoutUserInput, Prisma.BatchCheckUncheckedCreateWithoutUserInput> | Prisma.BatchCheckCreateWithoutUserInput[] | Prisma.BatchCheckUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BatchCheckCreateOrConnectWithoutUserInput | Prisma.BatchCheckCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BatchCheckCreateManyUserInputEnvelope
  connect?: Prisma.BatchCheckWhereUniqueInput | Prisma.BatchCheckWhereUniqueInput[]
}

export type BatchCheckUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BatchCheckCreateWithoutUserInput, Prisma.BatchCheckUncheckedCreateWithoutUserInput> | Prisma.BatchCheckCreateWithoutUserInput[] | Prisma.BatchCheckUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BatchCheckCreateOrConnectWithoutUserInput | Prisma.BatchCheckCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BatchCheckCreateManyUserInputEnvelope
  connect?: Prisma.BatchCheckWhereUniqueInput | Prisma.BatchCheckWhereUniqueInput[]
}

export type BatchCheckUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BatchCheckCreateWithoutUserInput, Prisma.BatchCheckUncheckedCreateWithoutUserInput> | Prisma.BatchCheckCreateWithoutUserInput[] | Prisma.BatchCheckUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BatchCheckCreateOrConnectWithoutUserInput | Prisma.BatchCheckCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BatchCheckUpsertWithWhereUniqueWithoutUserInput | Prisma.BatchCheckUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BatchCheckCreateManyUserInputEnvelope
  set?: Prisma.BatchCheckWhereUniqueInput | Prisma.BatchCheckWhereUniqueInput[]
  disconnect?: Prisma.BatchCheckWhereUniqueInput | Prisma.BatchCheckWhereUniqueInput[]
  delete?: Prisma.BatchCheckWhereUniqueInput | Prisma.BatchCheckWhereUniqueInput[]
  connect?: Prisma.BatchCheckWhereUniqueInput | Prisma.BatchCheckWhereUniqueInput[]
  update?: Prisma.BatchCheckUpdateWithWhereUniqueWithoutUserInput | Prisma.BatchCheckUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BatchCheckUpdateManyWithWhereWithoutUserInput | Prisma.BatchCheckUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BatchCheckScalarWhereInput | Prisma.BatchCheckScalarWhereInput[]
}

export type BatchCheckUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BatchCheckCreateWithoutUserInput, Prisma.BatchCheckUncheckedCreateWithoutUserInput> | Prisma.BatchCheckCreateWithoutUserInput[] | Prisma.BatchCheckUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BatchCheckCreateOrConnectWithoutUserInput | Prisma.BatchCheckCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BatchCheckUpsertWithWhereUniqueWithoutUserInput | Prisma.BatchCheckUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BatchCheckCreateManyUserInputEnvelope
  set?: Prisma.BatchCheckWhereUniqueInput | Prisma.BatchCheckWhereUniqueInput[]
  disconnect?: Prisma.BatchCheckWhereUniqueInput | Prisma.BatchCheckWhereUniqueInput[]
  delete?: Prisma.BatchCheckWhereUniqueInput | Prisma.BatchCheckWhereUniqueInput[]
  connect?: Prisma.BatchCheckWhereUniqueInput | Prisma.BatchCheckWhereUniqueInput[]
  update?: Prisma.BatchCheckUpdateWithWhereUniqueWithoutUserInput | Prisma.BatchCheckUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BatchCheckUpdateManyWithWhereWithoutUserInput | Prisma.BatchCheckUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BatchCheckScalarWhereInput | Prisma.BatchCheckScalarWhereInput[]
}

export type BatchCheckCreateNestedOneWithoutChecksInput = {
  create?: Prisma.XOR<Prisma.BatchCheckCreateWithoutChecksInput, Prisma.BatchCheckUncheckedCreateWithoutChecksInput>
  connectOrCreate?: Prisma.BatchCheckCreateOrConnectWithoutChecksInput
  connect?: Prisma.BatchCheckWhereUniqueInput
}

export type BatchCheckUpdateOneWithoutChecksNestedInput = {
  create?: Prisma.XOR<Prisma.BatchCheckCreateWithoutChecksInput, Prisma.BatchCheckUncheckedCreateWithoutChecksInput>
  connectOrCreate?: Prisma.BatchCheckCreateOrConnectWithoutChecksInput
  upsert?: Prisma.BatchCheckUpsertWithoutChecksInput
  disconnect?: Prisma.BatchCheckWhereInput | boolean
  delete?: Prisma.BatchCheckWhereInput | boolean
  connect?: Prisma.BatchCheckWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BatchCheckUpdateToOneWithWhereWithoutChecksInput, Prisma.BatchCheckUpdateWithoutChecksInput>, Prisma.BatchCheckUncheckedUpdateWithoutChecksInput>
}

export type BatchCheckCreateWithoutUserInput = {
  id?: string
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  totalItems: number
  successfulItems?: number
  failedItems?: number
  cost: number
  currentChunk?: number
  reportPath?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  checks?: Prisma.CheckCreateNestedManyWithoutBatchInput
}

export type BatchCheckUncheckedCreateWithoutUserInput = {
  id?: string
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  totalItems: number
  successfulItems?: number
  failedItems?: number
  cost: number
  currentChunk?: number
  reportPath?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  checks?: Prisma.CheckUncheckedCreateNestedManyWithoutBatchInput
}

export type BatchCheckCreateOrConnectWithoutUserInput = {
  where: Prisma.BatchCheckWhereUniqueInput
  create: Prisma.XOR<Prisma.BatchCheckCreateWithoutUserInput, Prisma.BatchCheckUncheckedCreateWithoutUserInput>
}

export type BatchCheckCreateManyUserInputEnvelope = {
  data: Prisma.BatchCheckCreateManyUserInput | Prisma.BatchCheckCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type BatchCheckUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.BatchCheckWhereUniqueInput
  update: Prisma.XOR<Prisma.BatchCheckUpdateWithoutUserInput, Prisma.BatchCheckUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.BatchCheckCreateWithoutUserInput, Prisma.BatchCheckUncheckedCreateWithoutUserInput>
}

export type BatchCheckUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.BatchCheckWhereUniqueInput
  data: Prisma.XOR<Prisma.BatchCheckUpdateWithoutUserInput, Prisma.BatchCheckUncheckedUpdateWithoutUserInput>
}

export type BatchCheckUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.BatchCheckScalarWhereInput
  data: Prisma.XOR<Prisma.BatchCheckUpdateManyMutationInput, Prisma.BatchCheckUncheckedUpdateManyWithoutUserInput>
}

export type BatchCheckScalarWhereInput = {
  AND?: Prisma.BatchCheckScalarWhereInput | Prisma.BatchCheckScalarWhereInput[]
  OR?: Prisma.BatchCheckScalarWhereInput[]
  NOT?: Prisma.BatchCheckScalarWhereInput | Prisma.BatchCheckScalarWhereInput[]
  id?: Prisma.StringFilter<"BatchCheck"> | string
  userId?: Prisma.StringFilter<"BatchCheck"> | string
  module?: Prisma.EnumCheckModuleEnumsFilter<"BatchCheck"> | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFilter<"BatchCheck"> | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntFilter<"BatchCheck"> | number
  successfulItems?: Prisma.IntFilter<"BatchCheck"> | number
  failedItems?: Prisma.IntFilter<"BatchCheck"> | number
  cost?: Prisma.IntFilter<"BatchCheck"> | number
  currentChunk?: Prisma.IntFilter<"BatchCheck"> | number
  reportPath?: Prisma.StringNullableFilter<"BatchCheck"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BatchCheck"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BatchCheck"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"BatchCheck"> | Date | string | null
}

export type BatchCheckCreateWithoutChecksInput = {
  id?: string
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  totalItems: number
  successfulItems?: number
  failedItems?: number
  cost: number
  currentChunk?: number
  reportPath?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutBatchesInput
}

export type BatchCheckUncheckedCreateWithoutChecksInput = {
  id?: string
  userId: string
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  totalItems: number
  successfulItems?: number
  failedItems?: number
  cost: number
  currentChunk?: number
  reportPath?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
}

export type BatchCheckCreateOrConnectWithoutChecksInput = {
  where: Prisma.BatchCheckWhereUniqueInput
  create: Prisma.XOR<Prisma.BatchCheckCreateWithoutChecksInput, Prisma.BatchCheckUncheckedCreateWithoutChecksInput>
}

export type BatchCheckUpsertWithoutChecksInput = {
  update: Prisma.XOR<Prisma.BatchCheckUpdateWithoutChecksInput, Prisma.BatchCheckUncheckedUpdateWithoutChecksInput>
  create: Prisma.XOR<Prisma.BatchCheckCreateWithoutChecksInput, Prisma.BatchCheckUncheckedCreateWithoutChecksInput>
  where?: Prisma.BatchCheckWhereInput
}

export type BatchCheckUpdateToOneWithWhereWithoutChecksInput = {
  where?: Prisma.BatchCheckWhereInput
  data: Prisma.XOR<Prisma.BatchCheckUpdateWithoutChecksInput, Prisma.BatchCheckUncheckedUpdateWithoutChecksInput>
}

export type BatchCheckUpdateWithoutChecksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntFieldUpdateOperationsInput | number
  successfulItems?: Prisma.IntFieldUpdateOperationsInput | number
  failedItems?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  currentChunk?: Prisma.IntFieldUpdateOperationsInput | number
  reportPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutBatchesNestedInput
}

export type BatchCheckUncheckedUpdateWithoutChecksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntFieldUpdateOperationsInput | number
  successfulItems?: Prisma.IntFieldUpdateOperationsInput | number
  failedItems?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  currentChunk?: Prisma.IntFieldUpdateOperationsInput | number
  reportPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BatchCheckCreateManyUserInput = {
  id?: string
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  totalItems: number
  successfulItems?: number
  failedItems?: number
  cost: number
  currentChunk?: number
  reportPath?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
}

export type BatchCheckUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntFieldUpdateOperationsInput | number
  successfulItems?: Prisma.IntFieldUpdateOperationsInput | number
  failedItems?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  currentChunk?: Prisma.IntFieldUpdateOperationsInput | number
  reportPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  checks?: Prisma.CheckUpdateManyWithoutBatchNestedInput
}

export type BatchCheckUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntFieldUpdateOperationsInput | number
  successfulItems?: Prisma.IntFieldUpdateOperationsInput | number
  failedItems?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  currentChunk?: Prisma.IntFieldUpdateOperationsInput | number
  reportPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  checks?: Prisma.CheckUncheckedUpdateManyWithoutBatchNestedInput
}

export type BatchCheckUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  totalItems?: Prisma.IntFieldUpdateOperationsInput | number
  successfulItems?: Prisma.IntFieldUpdateOperationsInput | number
  failedItems?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  currentChunk?: Prisma.IntFieldUpdateOperationsInput | number
  reportPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type BatchCheckCountOutputType
 */

export type BatchCheckCountOutputType = {
  checks: number
}

export type BatchCheckCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  checks?: boolean | BatchCheckCountOutputTypeCountChecksArgs
}

/**
 * BatchCheckCountOutputType without action
 */
export type BatchCheckCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheckCountOutputType
   */
  select?: Prisma.BatchCheckCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BatchCheckCountOutputType without action
 */
export type BatchCheckCountOutputTypeCountChecksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CheckWhereInput
}


export type BatchCheckSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  module?: boolean
  status?: boolean
  totalItems?: boolean
  successfulItems?: boolean
  failedItems?: boolean
  cost?: boolean
  currentChunk?: boolean
  reportPath?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  checks?: boolean | Prisma.BatchCheck$checksArgs<ExtArgs>
  _count?: boolean | Prisma.BatchCheckCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["batchCheck"]>

export type BatchCheckSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  module?: boolean
  status?: boolean
  totalItems?: boolean
  successfulItems?: boolean
  failedItems?: boolean
  cost?: boolean
  currentChunk?: boolean
  reportPath?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["batchCheck"]>

export type BatchCheckSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  module?: boolean
  status?: boolean
  totalItems?: boolean
  successfulItems?: boolean
  failedItems?: boolean
  cost?: boolean
  currentChunk?: boolean
  reportPath?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["batchCheck"]>

export type BatchCheckSelectScalar = {
  id?: boolean
  userId?: boolean
  module?: boolean
  status?: boolean
  totalItems?: boolean
  successfulItems?: boolean
  failedItems?: boolean
  cost?: boolean
  currentChunk?: boolean
  reportPath?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completedAt?: boolean
}

export type BatchCheckOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "module" | "status" | "totalItems" | "successfulItems" | "failedItems" | "cost" | "currentChunk" | "reportPath" | "createdAt" | "updatedAt" | "completedAt", ExtArgs["result"]["batchCheck"]>
export type BatchCheckInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  checks?: boolean | Prisma.BatchCheck$checksArgs<ExtArgs>
  _count?: boolean | Prisma.BatchCheckCountOutputTypeDefaultArgs<ExtArgs>
}
export type BatchCheckIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BatchCheckIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $BatchCheckPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BatchCheck"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    checks: Prisma.$CheckPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    module: $Enums.CheckModuleEnums
    status: $Enums.CheckStatusEnums
    totalItems: number
    successfulItems: number
    failedItems: number
    cost: number
    currentChunk: number
    reportPath: string | null
    createdAt: Date
    updatedAt: Date
    completedAt: Date | null
  }, ExtArgs["result"]["batchCheck"]>
  composites: {}
}

export type BatchCheckGetPayload<S extends boolean | null | undefined | BatchCheckDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload, S>

export type BatchCheckCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BatchCheckFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BatchCheckCountAggregateInputType | true
  }

export interface BatchCheckDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BatchCheck'], meta: { name: 'BatchCheck' } }
  /**
   * Find zero or one BatchCheck that matches the filter.
   * @param {BatchCheckFindUniqueArgs} args - Arguments to find a BatchCheck
   * @example
   * // Get one BatchCheck
   * const batchCheck = await prisma.batchCheck.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BatchCheckFindUniqueArgs>(args: Prisma.SelectSubset<T, BatchCheckFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BatchCheckClient<runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BatchCheck that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BatchCheckFindUniqueOrThrowArgs} args - Arguments to find a BatchCheck
   * @example
   * // Get one BatchCheck
   * const batchCheck = await prisma.batchCheck.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BatchCheckFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BatchCheckFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BatchCheckClient<runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BatchCheck that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchCheckFindFirstArgs} args - Arguments to find a BatchCheck
   * @example
   * // Get one BatchCheck
   * const batchCheck = await prisma.batchCheck.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BatchCheckFindFirstArgs>(args?: Prisma.SelectSubset<T, BatchCheckFindFirstArgs<ExtArgs>>): Prisma.Prisma__BatchCheckClient<runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BatchCheck that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchCheckFindFirstOrThrowArgs} args - Arguments to find a BatchCheck
   * @example
   * // Get one BatchCheck
   * const batchCheck = await prisma.batchCheck.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BatchCheckFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BatchCheckFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BatchCheckClient<runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BatchChecks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchCheckFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BatchChecks
   * const batchChecks = await prisma.batchCheck.findMany()
   * 
   * // Get first 10 BatchChecks
   * const batchChecks = await prisma.batchCheck.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const batchCheckWithIdOnly = await prisma.batchCheck.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BatchCheckFindManyArgs>(args?: Prisma.SelectSubset<T, BatchCheckFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BatchCheck.
   * @param {BatchCheckCreateArgs} args - Arguments to create a BatchCheck.
   * @example
   * // Create one BatchCheck
   * const BatchCheck = await prisma.batchCheck.create({
   *   data: {
   *     // ... data to create a BatchCheck
   *   }
   * })
   * 
   */
  create<T extends BatchCheckCreateArgs>(args: Prisma.SelectSubset<T, BatchCheckCreateArgs<ExtArgs>>): Prisma.Prisma__BatchCheckClient<runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BatchChecks.
   * @param {BatchCheckCreateManyArgs} args - Arguments to create many BatchChecks.
   * @example
   * // Create many BatchChecks
   * const batchCheck = await prisma.batchCheck.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BatchCheckCreateManyArgs>(args?: Prisma.SelectSubset<T, BatchCheckCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BatchChecks and returns the data saved in the database.
   * @param {BatchCheckCreateManyAndReturnArgs} args - Arguments to create many BatchChecks.
   * @example
   * // Create many BatchChecks
   * const batchCheck = await prisma.batchCheck.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BatchChecks and only return the `id`
   * const batchCheckWithIdOnly = await prisma.batchCheck.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BatchCheckCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BatchCheckCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BatchCheck.
   * @param {BatchCheckDeleteArgs} args - Arguments to delete one BatchCheck.
   * @example
   * // Delete one BatchCheck
   * const BatchCheck = await prisma.batchCheck.delete({
   *   where: {
   *     // ... filter to delete one BatchCheck
   *   }
   * })
   * 
   */
  delete<T extends BatchCheckDeleteArgs>(args: Prisma.SelectSubset<T, BatchCheckDeleteArgs<ExtArgs>>): Prisma.Prisma__BatchCheckClient<runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BatchCheck.
   * @param {BatchCheckUpdateArgs} args - Arguments to update one BatchCheck.
   * @example
   * // Update one BatchCheck
   * const batchCheck = await prisma.batchCheck.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BatchCheckUpdateArgs>(args: Prisma.SelectSubset<T, BatchCheckUpdateArgs<ExtArgs>>): Prisma.Prisma__BatchCheckClient<runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BatchChecks.
   * @param {BatchCheckDeleteManyArgs} args - Arguments to filter BatchChecks to delete.
   * @example
   * // Delete a few BatchChecks
   * const { count } = await prisma.batchCheck.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BatchCheckDeleteManyArgs>(args?: Prisma.SelectSubset<T, BatchCheckDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BatchChecks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchCheckUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BatchChecks
   * const batchCheck = await prisma.batchCheck.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BatchCheckUpdateManyArgs>(args: Prisma.SelectSubset<T, BatchCheckUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BatchChecks and returns the data updated in the database.
   * @param {BatchCheckUpdateManyAndReturnArgs} args - Arguments to update many BatchChecks.
   * @example
   * // Update many BatchChecks
   * const batchCheck = await prisma.batchCheck.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BatchChecks and only return the `id`
   * const batchCheckWithIdOnly = await prisma.batchCheck.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BatchCheckUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BatchCheckUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BatchCheck.
   * @param {BatchCheckUpsertArgs} args - Arguments to update or create a BatchCheck.
   * @example
   * // Update or create a BatchCheck
   * const batchCheck = await prisma.batchCheck.upsert({
   *   create: {
   *     // ... data to create a BatchCheck
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BatchCheck we want to update
   *   }
   * })
   */
  upsert<T extends BatchCheckUpsertArgs>(args: Prisma.SelectSubset<T, BatchCheckUpsertArgs<ExtArgs>>): Prisma.Prisma__BatchCheckClient<runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BatchChecks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchCheckCountArgs} args - Arguments to filter BatchChecks to count.
   * @example
   * // Count the number of BatchChecks
   * const count = await prisma.batchCheck.count({
   *   where: {
   *     // ... the filter for the BatchChecks we want to count
   *   }
   * })
  **/
  count<T extends BatchCheckCountArgs>(
    args?: Prisma.Subset<T, BatchCheckCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BatchCheckCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BatchCheck.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchCheckAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BatchCheckAggregateArgs>(args: Prisma.Subset<T, BatchCheckAggregateArgs>): Prisma.PrismaPromise<GetBatchCheckAggregateType<T>>

  /**
   * Group by BatchCheck.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchCheckGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BatchCheckGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BatchCheckGroupByArgs['orderBy'] }
      : { orderBy?: BatchCheckGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BatchCheckGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBatchCheckGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BatchCheck model
 */
readonly fields: BatchCheckFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BatchCheck.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BatchCheckClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  checks<T extends Prisma.BatchCheck$checksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BatchCheck$checksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BatchCheck model
 */
export interface BatchCheckFieldRefs {
  readonly id: Prisma.FieldRef<"BatchCheck", 'String'>
  readonly userId: Prisma.FieldRef<"BatchCheck", 'String'>
  readonly module: Prisma.FieldRef<"BatchCheck", 'CheckModuleEnums'>
  readonly status: Prisma.FieldRef<"BatchCheck", 'CheckStatusEnums'>
  readonly totalItems: Prisma.FieldRef<"BatchCheck", 'Int'>
  readonly successfulItems: Prisma.FieldRef<"BatchCheck", 'Int'>
  readonly failedItems: Prisma.FieldRef<"BatchCheck", 'Int'>
  readonly cost: Prisma.FieldRef<"BatchCheck", 'Int'>
  readonly currentChunk: Prisma.FieldRef<"BatchCheck", 'Int'>
  readonly reportPath: Prisma.FieldRef<"BatchCheck", 'String'>
  readonly createdAt: Prisma.FieldRef<"BatchCheck", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BatchCheck", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"BatchCheck", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BatchCheck findUnique
 */
export type BatchCheckFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckInclude<ExtArgs> | null
  /**
   * Filter, which BatchCheck to fetch.
   */
  where: Prisma.BatchCheckWhereUniqueInput
}

/**
 * BatchCheck findUniqueOrThrow
 */
export type BatchCheckFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckInclude<ExtArgs> | null
  /**
   * Filter, which BatchCheck to fetch.
   */
  where: Prisma.BatchCheckWhereUniqueInput
}

/**
 * BatchCheck findFirst
 */
export type BatchCheckFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckInclude<ExtArgs> | null
  /**
   * Filter, which BatchCheck to fetch.
   */
  where?: Prisma.BatchCheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BatchChecks to fetch.
   */
  orderBy?: Prisma.BatchCheckOrderByWithRelationInput | Prisma.BatchCheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BatchChecks.
   */
  cursor?: Prisma.BatchCheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BatchChecks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BatchChecks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BatchChecks.
   */
  distinct?: Prisma.BatchCheckScalarFieldEnum | Prisma.BatchCheckScalarFieldEnum[]
}

/**
 * BatchCheck findFirstOrThrow
 */
export type BatchCheckFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckInclude<ExtArgs> | null
  /**
   * Filter, which BatchCheck to fetch.
   */
  where?: Prisma.BatchCheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BatchChecks to fetch.
   */
  orderBy?: Prisma.BatchCheckOrderByWithRelationInput | Prisma.BatchCheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BatchChecks.
   */
  cursor?: Prisma.BatchCheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BatchChecks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BatchChecks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BatchChecks.
   */
  distinct?: Prisma.BatchCheckScalarFieldEnum | Prisma.BatchCheckScalarFieldEnum[]
}

/**
 * BatchCheck findMany
 */
export type BatchCheckFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckInclude<ExtArgs> | null
  /**
   * Filter, which BatchChecks to fetch.
   */
  where?: Prisma.BatchCheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BatchChecks to fetch.
   */
  orderBy?: Prisma.BatchCheckOrderByWithRelationInput | Prisma.BatchCheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BatchChecks.
   */
  cursor?: Prisma.BatchCheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BatchChecks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BatchChecks.
   */
  skip?: number
  distinct?: Prisma.BatchCheckScalarFieldEnum | Prisma.BatchCheckScalarFieldEnum[]
}

/**
 * BatchCheck create
 */
export type BatchCheckCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckInclude<ExtArgs> | null
  /**
   * The data needed to create a BatchCheck.
   */
  data: Prisma.XOR<Prisma.BatchCheckCreateInput, Prisma.BatchCheckUncheckedCreateInput>
}

/**
 * BatchCheck createMany
 */
export type BatchCheckCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BatchChecks.
   */
  data: Prisma.BatchCheckCreateManyInput | Prisma.BatchCheckCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BatchCheck createManyAndReturn
 */
export type BatchCheckCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * The data used to create many BatchChecks.
   */
  data: Prisma.BatchCheckCreateManyInput | Prisma.BatchCheckCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BatchCheck update
 */
export type BatchCheckUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckInclude<ExtArgs> | null
  /**
   * The data needed to update a BatchCheck.
   */
  data: Prisma.XOR<Prisma.BatchCheckUpdateInput, Prisma.BatchCheckUncheckedUpdateInput>
  /**
   * Choose, which BatchCheck to update.
   */
  where: Prisma.BatchCheckWhereUniqueInput
}

/**
 * BatchCheck updateMany
 */
export type BatchCheckUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BatchChecks.
   */
  data: Prisma.XOR<Prisma.BatchCheckUpdateManyMutationInput, Prisma.BatchCheckUncheckedUpdateManyInput>
  /**
   * Filter which BatchChecks to update
   */
  where?: Prisma.BatchCheckWhereInput
  /**
   * Limit how many BatchChecks to update.
   */
  limit?: number
}

/**
 * BatchCheck updateManyAndReturn
 */
export type BatchCheckUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * The data used to update BatchChecks.
   */
  data: Prisma.XOR<Prisma.BatchCheckUpdateManyMutationInput, Prisma.BatchCheckUncheckedUpdateManyInput>
  /**
   * Filter which BatchChecks to update
   */
  where?: Prisma.BatchCheckWhereInput
  /**
   * Limit how many BatchChecks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BatchCheck upsert
 */
export type BatchCheckUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckInclude<ExtArgs> | null
  /**
   * The filter to search for the BatchCheck to update in case it exists.
   */
  where: Prisma.BatchCheckWhereUniqueInput
  /**
   * In case the BatchCheck found by the `where` argument doesn't exist, create a new BatchCheck with this data.
   */
  create: Prisma.XOR<Prisma.BatchCheckCreateInput, Prisma.BatchCheckUncheckedCreateInput>
  /**
   * In case the BatchCheck was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BatchCheckUpdateInput, Prisma.BatchCheckUncheckedUpdateInput>
}

/**
 * BatchCheck delete
 */
export type BatchCheckDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckInclude<ExtArgs> | null
  /**
   * Filter which BatchCheck to delete.
   */
  where: Prisma.BatchCheckWhereUniqueInput
}

/**
 * BatchCheck deleteMany
 */
export type BatchCheckDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BatchChecks to delete
   */
  where?: Prisma.BatchCheckWhereInput
  /**
   * Limit how many BatchChecks to delete.
   */
  limit?: number
}

/**
 * BatchCheck.checks
 */
export type BatchCheck$checksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckInclude<ExtArgs> | null
  where?: Prisma.CheckWhereInput
  orderBy?: Prisma.CheckOrderByWithRelationInput | Prisma.CheckOrderByWithRelationInput[]
  cursor?: Prisma.CheckWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CheckScalarFieldEnum | Prisma.CheckScalarFieldEnum[]
}

/**
 * BatchCheck without action
 */
export type BatchCheckDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckInclude<ExtArgs> | null
}
