
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Check` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Check
 * 
 */
export type CheckModel = runtime.Types.Result.DefaultSelection<Prisma.$CheckPayload>

export type AggregateCheck = {
  _count: CheckCountAggregateOutputType | null
  _avg: CheckAvgAggregateOutputType | null
  _sum: CheckSumAggregateOutputType | null
  _min: CheckMinAggregateOutputType | null
  _max: CheckMaxAggregateOutputType | null
}

export type CheckAvgAggregateOutputType = {
  batchPosition: number | null
  sourceRow: number | null
  cost: number | null
}

export type CheckSumAggregateOutputType = {
  batchPosition: number | null
  sourceRow: number | null
  cost: number | null
}

export type CheckMinAggregateOutputType = {
  id: string | null
  userId: string | null
  batchId: string | null
  batchPosition: number | null
  sourceRow: number | null
  serviceId: string | null
  provider: $Enums.CheckProviderEnums | null
  module: $Enums.CheckModuleEnums | null
  status: $Enums.CheckStatusEnums | null
  cost: number | null
  balanceRefund: boolean | null
  subjectBodyText: string | null
  idempotencyKey: string | null
  createdAt: Date | null
  updatedAt: Date | null
  completedAt: Date | null
}

export type CheckMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  batchId: string | null
  batchPosition: number | null
  sourceRow: number | null
  serviceId: string | null
  provider: $Enums.CheckProviderEnums | null
  module: $Enums.CheckModuleEnums | null
  status: $Enums.CheckStatusEnums | null
  cost: number | null
  balanceRefund: boolean | null
  subjectBodyText: string | null
  idempotencyKey: string | null
  createdAt: Date | null
  updatedAt: Date | null
  completedAt: Date | null
}

export type CheckCountAggregateOutputType = {
  id: number
  userId: number
  batchId: number
  batchPosition: number
  sourceRow: number
  serviceId: number
  provider: number
  module: number
  status: number
  cost: number
  balanceRefund: number
  subjectBody: number
  subjectBodyText: number
  result: number
  error: number
  idempotencyKey: number
  createdAt: number
  updatedAt: number
  completedAt: number
  _all: number
}


export type CheckAvgAggregateInputType = {
  batchPosition?: true
  sourceRow?: true
  cost?: true
}

export type CheckSumAggregateInputType = {
  batchPosition?: true
  sourceRow?: true
  cost?: true
}

export type CheckMinAggregateInputType = {
  id?: true
  userId?: true
  batchId?: true
  batchPosition?: true
  sourceRow?: true
  serviceId?: true
  provider?: true
  module?: true
  status?: true
  cost?: true
  balanceRefund?: true
  subjectBodyText?: true
  idempotencyKey?: true
  createdAt?: true
  updatedAt?: true
  completedAt?: true
}

export type CheckMaxAggregateInputType = {
  id?: true
  userId?: true
  batchId?: true
  batchPosition?: true
  sourceRow?: true
  serviceId?: true
  provider?: true
  module?: true
  status?: true
  cost?: true
  balanceRefund?: true
  subjectBodyText?: true
  idempotencyKey?: true
  createdAt?: true
  updatedAt?: true
  completedAt?: true
}

export type CheckCountAggregateInputType = {
  id?: true
  userId?: true
  batchId?: true
  batchPosition?: true
  sourceRow?: true
  serviceId?: true
  provider?: true
  module?: true
  status?: true
  cost?: true
  balanceRefund?: true
  subjectBody?: true
  subjectBodyText?: true
  result?: true
  error?: true
  idempotencyKey?: true
  createdAt?: true
  updatedAt?: true
  completedAt?: true
  _all?: true
}

export type CheckAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Check to aggregate.
   */
  where?: Prisma.CheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checks to fetch.
   */
  orderBy?: Prisma.CheckOrderByWithRelationInput | Prisma.CheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Checks
  **/
  _count?: true | CheckCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CheckAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CheckSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CheckMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CheckMaxAggregateInputType
}

export type GetCheckAggregateType<T extends CheckAggregateArgs> = {
      [P in keyof T & keyof AggregateCheck]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCheck[P]>
    : Prisma.GetScalarType<T[P], AggregateCheck[P]>
}




export type CheckGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CheckWhereInput
  orderBy?: Prisma.CheckOrderByWithAggregationInput | Prisma.CheckOrderByWithAggregationInput[]
  by: Prisma.CheckScalarFieldEnum[] | Prisma.CheckScalarFieldEnum
  having?: Prisma.CheckScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CheckCountAggregateInputType | true
  _avg?: CheckAvgAggregateInputType
  _sum?: CheckSumAggregateInputType
  _min?: CheckMinAggregateInputType
  _max?: CheckMaxAggregateInputType
}

export type CheckGroupByOutputType = {
  id: string
  userId: string
  batchId: string | null
  batchPosition: number | null
  sourceRow: number | null
  serviceId: string | null
  provider: $Enums.CheckProviderEnums
  module: $Enums.CheckModuleEnums
  status: $Enums.CheckStatusEnums
  cost: number
  balanceRefund: boolean
  subjectBody: runtime.JsonValue
  subjectBodyText: string
  result: runtime.JsonValue | null
  error: runtime.JsonValue | null
  idempotencyKey: string
  createdAt: Date
  updatedAt: Date
  completedAt: Date | null
  _count: CheckCountAggregateOutputType | null
  _avg: CheckAvgAggregateOutputType | null
  _sum: CheckSumAggregateOutputType | null
  _min: CheckMinAggregateOutputType | null
  _max: CheckMaxAggregateOutputType | null
}

type GetCheckGroupByPayload<T extends CheckGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CheckGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CheckGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CheckGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CheckGroupByOutputType[P]>
      }
    >
  >



export type CheckWhereInput = {
  AND?: Prisma.CheckWhereInput | Prisma.CheckWhereInput[]
  OR?: Prisma.CheckWhereInput[]
  NOT?: Prisma.CheckWhereInput | Prisma.CheckWhereInput[]
  id?: Prisma.StringFilter<"Check"> | string
  userId?: Prisma.StringFilter<"Check"> | string
  batchId?: Prisma.StringNullableFilter<"Check"> | string | null
  batchPosition?: Prisma.IntNullableFilter<"Check"> | number | null
  sourceRow?: Prisma.IntNullableFilter<"Check"> | number | null
  serviceId?: Prisma.StringNullableFilter<"Check"> | string | null
  provider?: Prisma.EnumCheckProviderEnumsFilter<"Check"> | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFilter<"Check"> | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFilter<"Check"> | $Enums.CheckStatusEnums
  cost?: Prisma.IntFilter<"Check"> | number
  balanceRefund?: Prisma.BoolFilter<"Check"> | boolean
  subjectBody?: Prisma.JsonFilter<"Check">
  subjectBodyText?: Prisma.StringFilter<"Check"> | string
  result?: Prisma.JsonNullableFilter<"Check">
  error?: Prisma.JsonNullableFilter<"Check">
  idempotencyKey?: Prisma.StringFilter<"Check"> | string
  createdAt?: Prisma.DateTimeFilter<"Check"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Check"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"Check"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  batch?: Prisma.XOR<Prisma.BatchCheckNullableScalarRelationFilter, Prisma.BatchCheckWhereInput> | null
}

export type CheckOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  batchId?: Prisma.SortOrderInput | Prisma.SortOrder
  batchPosition?: Prisma.SortOrderInput | Prisma.SortOrder
  sourceRow?: Prisma.SortOrderInput | Prisma.SortOrder
  serviceId?: Prisma.SortOrderInput | Prisma.SortOrder
  provider?: Prisma.SortOrder
  module?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  balanceRefund?: Prisma.SortOrder
  subjectBody?: Prisma.SortOrder
  subjectBodyText?: Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  idempotencyKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  batch?: Prisma.BatchCheckOrderByWithRelationInput
}

export type CheckWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  idempotencyKey?: string
  AND?: Prisma.CheckWhereInput | Prisma.CheckWhereInput[]
  OR?: Prisma.CheckWhereInput[]
  NOT?: Prisma.CheckWhereInput | Prisma.CheckWhereInput[]
  userId?: Prisma.StringFilter<"Check"> | string
  batchId?: Prisma.StringNullableFilter<"Check"> | string | null
  batchPosition?: Prisma.IntNullableFilter<"Check"> | number | null
  sourceRow?: Prisma.IntNullableFilter<"Check"> | number | null
  serviceId?: Prisma.StringNullableFilter<"Check"> | string | null
  provider?: Prisma.EnumCheckProviderEnumsFilter<"Check"> | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFilter<"Check"> | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFilter<"Check"> | $Enums.CheckStatusEnums
  cost?: Prisma.IntFilter<"Check"> | number
  balanceRefund?: Prisma.BoolFilter<"Check"> | boolean
  subjectBody?: Prisma.JsonFilter<"Check">
  subjectBodyText?: Prisma.StringFilter<"Check"> | string
  result?: Prisma.JsonNullableFilter<"Check">
  error?: Prisma.JsonNullableFilter<"Check">
  createdAt?: Prisma.DateTimeFilter<"Check"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Check"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"Check"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  batch?: Prisma.XOR<Prisma.BatchCheckNullableScalarRelationFilter, Prisma.BatchCheckWhereInput> | null
}, "id" | "idempotencyKey">

export type CheckOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  batchId?: Prisma.SortOrderInput | Prisma.SortOrder
  batchPosition?: Prisma.SortOrderInput | Prisma.SortOrder
  sourceRow?: Prisma.SortOrderInput | Prisma.SortOrder
  serviceId?: Prisma.SortOrderInput | Prisma.SortOrder
  provider?: Prisma.SortOrder
  module?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  balanceRefund?: Prisma.SortOrder
  subjectBody?: Prisma.SortOrder
  subjectBodyText?: Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  idempotencyKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.CheckCountOrderByAggregateInput
  _avg?: Prisma.CheckAvgOrderByAggregateInput
  _max?: Prisma.CheckMaxOrderByAggregateInput
  _min?: Prisma.CheckMinOrderByAggregateInput
  _sum?: Prisma.CheckSumOrderByAggregateInput
}

export type CheckScalarWhereWithAggregatesInput = {
  AND?: Prisma.CheckScalarWhereWithAggregatesInput | Prisma.CheckScalarWhereWithAggregatesInput[]
  OR?: Prisma.CheckScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CheckScalarWhereWithAggregatesInput | Prisma.CheckScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Check"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Check"> | string
  batchId?: Prisma.StringNullableWithAggregatesFilter<"Check"> | string | null
  batchPosition?: Prisma.IntNullableWithAggregatesFilter<"Check"> | number | null
  sourceRow?: Prisma.IntNullableWithAggregatesFilter<"Check"> | number | null
  serviceId?: Prisma.StringNullableWithAggregatesFilter<"Check"> | string | null
  provider?: Prisma.EnumCheckProviderEnumsWithAggregatesFilter<"Check"> | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsWithAggregatesFilter<"Check"> | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsWithAggregatesFilter<"Check"> | $Enums.CheckStatusEnums
  cost?: Prisma.IntWithAggregatesFilter<"Check"> | number
  balanceRefund?: Prisma.BoolWithAggregatesFilter<"Check"> | boolean
  subjectBody?: Prisma.JsonWithAggregatesFilter<"Check">
  subjectBodyText?: Prisma.StringWithAggregatesFilter<"Check"> | string
  result?: Prisma.JsonNullableWithAggregatesFilter<"Check">
  error?: Prisma.JsonNullableWithAggregatesFilter<"Check">
  idempotencyKey?: Prisma.StringWithAggregatesFilter<"Check"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Check"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Check"> | Date | string
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Check"> | Date | string | null
}

export type CheckCreateInput = {
  id?: string
  batchPosition?: number | null
  sourceRow?: number | null
  serviceId?: string | null
  provider?: $Enums.CheckProviderEnums
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  cost: number
  balanceRefund?: boolean
  subjectBody: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText: string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutChecksInput
  batch?: Prisma.BatchCheckCreateNestedOneWithoutChecksInput
}

export type CheckUncheckedCreateInput = {
  id?: string
  userId: string
  batchId?: string | null
  batchPosition?: number | null
  sourceRow?: number | null
  serviceId?: string | null
  provider?: $Enums.CheckProviderEnums
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  cost: number
  balanceRefund?: boolean
  subjectBody: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText: string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
}

export type CheckUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchPosition?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sourceRow?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  serviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.EnumCheckProviderEnumsFieldUpdateOperationsInput | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  balanceRefund?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subjectBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutChecksNestedInput
  batch?: Prisma.BatchCheckUpdateOneWithoutChecksNestedInput
}

export type CheckUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  batchPosition?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sourceRow?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  serviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.EnumCheckProviderEnumsFieldUpdateOperationsInput | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  balanceRefund?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subjectBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CheckCreateManyInput = {
  id?: string
  userId: string
  batchId?: string | null
  batchPosition?: number | null
  sourceRow?: number | null
  serviceId?: string | null
  provider?: $Enums.CheckProviderEnums
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  cost: number
  balanceRefund?: boolean
  subjectBody: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText: string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
}

export type CheckUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchPosition?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sourceRow?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  serviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.EnumCheckProviderEnumsFieldUpdateOperationsInput | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  balanceRefund?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subjectBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CheckUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  batchPosition?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sourceRow?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  serviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.EnumCheckProviderEnumsFieldUpdateOperationsInput | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  balanceRefund?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subjectBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CheckListRelationFilter = {
  every?: Prisma.CheckWhereInput
  some?: Prisma.CheckWhereInput
  none?: Prisma.CheckWhereInput
}

export type CheckOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CheckCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  batchPosition?: Prisma.SortOrder
  sourceRow?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  module?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  balanceRefund?: Prisma.SortOrder
  subjectBody?: Prisma.SortOrder
  subjectBodyText?: Prisma.SortOrder
  result?: Prisma.SortOrder
  error?: Prisma.SortOrder
  idempotencyKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type CheckAvgOrderByAggregateInput = {
  batchPosition?: Prisma.SortOrder
  sourceRow?: Prisma.SortOrder
  cost?: Prisma.SortOrder
}

export type CheckMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  batchPosition?: Prisma.SortOrder
  sourceRow?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  module?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  balanceRefund?: Prisma.SortOrder
  subjectBodyText?: Prisma.SortOrder
  idempotencyKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type CheckMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  batchPosition?: Prisma.SortOrder
  sourceRow?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  module?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  balanceRefund?: Prisma.SortOrder
  subjectBodyText?: Prisma.SortOrder
  idempotencyKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type CheckSumOrderByAggregateInput = {
  batchPosition?: Prisma.SortOrder
  sourceRow?: Prisma.SortOrder
  cost?: Prisma.SortOrder
}

export type CheckCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CheckCreateWithoutUserInput, Prisma.CheckUncheckedCreateWithoutUserInput> | Prisma.CheckCreateWithoutUserInput[] | Prisma.CheckUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CheckCreateOrConnectWithoutUserInput | Prisma.CheckCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CheckCreateManyUserInputEnvelope
  connect?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
}

export type CheckUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CheckCreateWithoutUserInput, Prisma.CheckUncheckedCreateWithoutUserInput> | Prisma.CheckCreateWithoutUserInput[] | Prisma.CheckUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CheckCreateOrConnectWithoutUserInput | Prisma.CheckCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CheckCreateManyUserInputEnvelope
  connect?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
}

export type CheckUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CheckCreateWithoutUserInput, Prisma.CheckUncheckedCreateWithoutUserInput> | Prisma.CheckCreateWithoutUserInput[] | Prisma.CheckUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CheckCreateOrConnectWithoutUserInput | Prisma.CheckCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CheckUpsertWithWhereUniqueWithoutUserInput | Prisma.CheckUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CheckCreateManyUserInputEnvelope
  set?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  disconnect?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  delete?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  connect?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  update?: Prisma.CheckUpdateWithWhereUniqueWithoutUserInput | Prisma.CheckUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CheckUpdateManyWithWhereWithoutUserInput | Prisma.CheckUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CheckScalarWhereInput | Prisma.CheckScalarWhereInput[]
}

export type CheckUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CheckCreateWithoutUserInput, Prisma.CheckUncheckedCreateWithoutUserInput> | Prisma.CheckCreateWithoutUserInput[] | Prisma.CheckUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CheckCreateOrConnectWithoutUserInput | Prisma.CheckCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CheckUpsertWithWhereUniqueWithoutUserInput | Prisma.CheckUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CheckCreateManyUserInputEnvelope
  set?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  disconnect?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  delete?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  connect?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  update?: Prisma.CheckUpdateWithWhereUniqueWithoutUserInput | Prisma.CheckUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CheckUpdateManyWithWhereWithoutUserInput | Prisma.CheckUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CheckScalarWhereInput | Prisma.CheckScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EnumCheckProviderEnumsFieldUpdateOperationsInput = {
  set?: $Enums.CheckProviderEnums
}

export type EnumCheckStatusEnumsFieldUpdateOperationsInput = {
  set?: $Enums.CheckStatusEnums
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type CheckCreateNestedManyWithoutBatchInput = {
  create?: Prisma.XOR<Prisma.CheckCreateWithoutBatchInput, Prisma.CheckUncheckedCreateWithoutBatchInput> | Prisma.CheckCreateWithoutBatchInput[] | Prisma.CheckUncheckedCreateWithoutBatchInput[]
  connectOrCreate?: Prisma.CheckCreateOrConnectWithoutBatchInput | Prisma.CheckCreateOrConnectWithoutBatchInput[]
  createMany?: Prisma.CheckCreateManyBatchInputEnvelope
  connect?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
}

export type CheckUncheckedCreateNestedManyWithoutBatchInput = {
  create?: Prisma.XOR<Prisma.CheckCreateWithoutBatchInput, Prisma.CheckUncheckedCreateWithoutBatchInput> | Prisma.CheckCreateWithoutBatchInput[] | Prisma.CheckUncheckedCreateWithoutBatchInput[]
  connectOrCreate?: Prisma.CheckCreateOrConnectWithoutBatchInput | Prisma.CheckCreateOrConnectWithoutBatchInput[]
  createMany?: Prisma.CheckCreateManyBatchInputEnvelope
  connect?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
}

export type CheckUpdateManyWithoutBatchNestedInput = {
  create?: Prisma.XOR<Prisma.CheckCreateWithoutBatchInput, Prisma.CheckUncheckedCreateWithoutBatchInput> | Prisma.CheckCreateWithoutBatchInput[] | Prisma.CheckUncheckedCreateWithoutBatchInput[]
  connectOrCreate?: Prisma.CheckCreateOrConnectWithoutBatchInput | Prisma.CheckCreateOrConnectWithoutBatchInput[]
  upsert?: Prisma.CheckUpsertWithWhereUniqueWithoutBatchInput | Prisma.CheckUpsertWithWhereUniqueWithoutBatchInput[]
  createMany?: Prisma.CheckCreateManyBatchInputEnvelope
  set?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  disconnect?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  delete?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  connect?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  update?: Prisma.CheckUpdateWithWhereUniqueWithoutBatchInput | Prisma.CheckUpdateWithWhereUniqueWithoutBatchInput[]
  updateMany?: Prisma.CheckUpdateManyWithWhereWithoutBatchInput | Prisma.CheckUpdateManyWithWhereWithoutBatchInput[]
  deleteMany?: Prisma.CheckScalarWhereInput | Prisma.CheckScalarWhereInput[]
}

export type CheckUncheckedUpdateManyWithoutBatchNestedInput = {
  create?: Prisma.XOR<Prisma.CheckCreateWithoutBatchInput, Prisma.CheckUncheckedCreateWithoutBatchInput> | Prisma.CheckCreateWithoutBatchInput[] | Prisma.CheckUncheckedCreateWithoutBatchInput[]
  connectOrCreate?: Prisma.CheckCreateOrConnectWithoutBatchInput | Prisma.CheckCreateOrConnectWithoutBatchInput[]
  upsert?: Prisma.CheckUpsertWithWhereUniqueWithoutBatchInput | Prisma.CheckUpsertWithWhereUniqueWithoutBatchInput[]
  createMany?: Prisma.CheckCreateManyBatchInputEnvelope
  set?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  disconnect?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  delete?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  connect?: Prisma.CheckWhereUniqueInput | Prisma.CheckWhereUniqueInput[]
  update?: Prisma.CheckUpdateWithWhereUniqueWithoutBatchInput | Prisma.CheckUpdateWithWhereUniqueWithoutBatchInput[]
  updateMany?: Prisma.CheckUpdateManyWithWhereWithoutBatchInput | Prisma.CheckUpdateManyWithWhereWithoutBatchInput[]
  deleteMany?: Prisma.CheckScalarWhereInput | Prisma.CheckScalarWhereInput[]
}

export type CheckCreateWithoutUserInput = {
  id?: string
  batchPosition?: number | null
  sourceRow?: number | null
  serviceId?: string | null
  provider?: $Enums.CheckProviderEnums
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  cost: number
  balanceRefund?: boolean
  subjectBody: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText: string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  batch?: Prisma.BatchCheckCreateNestedOneWithoutChecksInput
}

export type CheckUncheckedCreateWithoutUserInput = {
  id?: string
  batchId?: string | null
  batchPosition?: number | null
  sourceRow?: number | null
  serviceId?: string | null
  provider?: $Enums.CheckProviderEnums
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  cost: number
  balanceRefund?: boolean
  subjectBody: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText: string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
}

export type CheckCreateOrConnectWithoutUserInput = {
  where: Prisma.CheckWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckCreateWithoutUserInput, Prisma.CheckUncheckedCreateWithoutUserInput>
}

export type CheckCreateManyUserInputEnvelope = {
  data: Prisma.CheckCreateManyUserInput | Prisma.CheckCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type CheckUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.CheckWhereUniqueInput
  update: Prisma.XOR<Prisma.CheckUpdateWithoutUserInput, Prisma.CheckUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CheckCreateWithoutUserInput, Prisma.CheckUncheckedCreateWithoutUserInput>
}

export type CheckUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.CheckWhereUniqueInput
  data: Prisma.XOR<Prisma.CheckUpdateWithoutUserInput, Prisma.CheckUncheckedUpdateWithoutUserInput>
}

export type CheckUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.CheckScalarWhereInput
  data: Prisma.XOR<Prisma.CheckUpdateManyMutationInput, Prisma.CheckUncheckedUpdateManyWithoutUserInput>
}

export type CheckScalarWhereInput = {
  AND?: Prisma.CheckScalarWhereInput | Prisma.CheckScalarWhereInput[]
  OR?: Prisma.CheckScalarWhereInput[]
  NOT?: Prisma.CheckScalarWhereInput | Prisma.CheckScalarWhereInput[]
  id?: Prisma.StringFilter<"Check"> | string
  userId?: Prisma.StringFilter<"Check"> | string
  batchId?: Prisma.StringNullableFilter<"Check"> | string | null
  batchPosition?: Prisma.IntNullableFilter<"Check"> | number | null
  sourceRow?: Prisma.IntNullableFilter<"Check"> | number | null
  serviceId?: Prisma.StringNullableFilter<"Check"> | string | null
  provider?: Prisma.EnumCheckProviderEnumsFilter<"Check"> | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFilter<"Check"> | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFilter<"Check"> | $Enums.CheckStatusEnums
  cost?: Prisma.IntFilter<"Check"> | number
  balanceRefund?: Prisma.BoolFilter<"Check"> | boolean
  subjectBody?: Prisma.JsonFilter<"Check">
  subjectBodyText?: Prisma.StringFilter<"Check"> | string
  result?: Prisma.JsonNullableFilter<"Check">
  error?: Prisma.JsonNullableFilter<"Check">
  idempotencyKey?: Prisma.StringFilter<"Check"> | string
  createdAt?: Prisma.DateTimeFilter<"Check"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Check"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"Check"> | Date | string | null
}

export type CheckCreateWithoutBatchInput = {
  id?: string
  batchPosition?: number | null
  sourceRow?: number | null
  serviceId?: string | null
  provider?: $Enums.CheckProviderEnums
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  cost: number
  balanceRefund?: boolean
  subjectBody: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText: string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutChecksInput
}

export type CheckUncheckedCreateWithoutBatchInput = {
  id?: string
  userId: string
  batchPosition?: number | null
  sourceRow?: number | null
  serviceId?: string | null
  provider?: $Enums.CheckProviderEnums
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  cost: number
  balanceRefund?: boolean
  subjectBody: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText: string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
}

export type CheckCreateOrConnectWithoutBatchInput = {
  where: Prisma.CheckWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckCreateWithoutBatchInput, Prisma.CheckUncheckedCreateWithoutBatchInput>
}

export type CheckCreateManyBatchInputEnvelope = {
  data: Prisma.CheckCreateManyBatchInput | Prisma.CheckCreateManyBatchInput[]
  skipDuplicates?: boolean
}

export type CheckUpsertWithWhereUniqueWithoutBatchInput = {
  where: Prisma.CheckWhereUniqueInput
  update: Prisma.XOR<Prisma.CheckUpdateWithoutBatchInput, Prisma.CheckUncheckedUpdateWithoutBatchInput>
  create: Prisma.XOR<Prisma.CheckCreateWithoutBatchInput, Prisma.CheckUncheckedCreateWithoutBatchInput>
}

export type CheckUpdateWithWhereUniqueWithoutBatchInput = {
  where: Prisma.CheckWhereUniqueInput
  data: Prisma.XOR<Prisma.CheckUpdateWithoutBatchInput, Prisma.CheckUncheckedUpdateWithoutBatchInput>
}

export type CheckUpdateManyWithWhereWithoutBatchInput = {
  where: Prisma.CheckScalarWhereInput
  data: Prisma.XOR<Prisma.CheckUpdateManyMutationInput, Prisma.CheckUncheckedUpdateManyWithoutBatchInput>
}

export type CheckCreateManyUserInput = {
  id?: string
  batchId?: string | null
  batchPosition?: number | null
  sourceRow?: number | null
  serviceId?: string | null
  provider?: $Enums.CheckProviderEnums
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  cost: number
  balanceRefund?: boolean
  subjectBody: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText: string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
}

export type CheckUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchPosition?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sourceRow?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  serviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.EnumCheckProviderEnumsFieldUpdateOperationsInput | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  balanceRefund?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subjectBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  batch?: Prisma.BatchCheckUpdateOneWithoutChecksNestedInput
}

export type CheckUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  batchPosition?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sourceRow?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  serviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.EnumCheckProviderEnumsFieldUpdateOperationsInput | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  balanceRefund?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subjectBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CheckUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  batchPosition?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sourceRow?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  serviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.EnumCheckProviderEnumsFieldUpdateOperationsInput | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  balanceRefund?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subjectBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CheckCreateManyBatchInput = {
  id?: string
  userId: string
  batchPosition?: number | null
  sourceRow?: number | null
  serviceId?: string | null
  provider?: $Enums.CheckProviderEnums
  module: $Enums.CheckModuleEnums
  status?: $Enums.CheckStatusEnums
  cost: number
  balanceRefund?: boolean
  subjectBody: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText: string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
}

export type CheckUpdateWithoutBatchInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchPosition?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sourceRow?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  serviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.EnumCheckProviderEnumsFieldUpdateOperationsInput | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  balanceRefund?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subjectBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutChecksNestedInput
}

export type CheckUncheckedUpdateWithoutBatchInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  batchPosition?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sourceRow?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  serviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.EnumCheckProviderEnumsFieldUpdateOperationsInput | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  balanceRefund?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subjectBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CheckUncheckedUpdateManyWithoutBatchInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  batchPosition?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sourceRow?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  serviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.EnumCheckProviderEnumsFieldUpdateOperationsInput | $Enums.CheckProviderEnums
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  status?: Prisma.EnumCheckStatusEnumsFieldUpdateOperationsInput | $Enums.CheckStatusEnums
  cost?: Prisma.IntFieldUpdateOperationsInput | number
  balanceRefund?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subjectBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  subjectBodyText?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idempotencyKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type CheckSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  batchId?: boolean
  batchPosition?: boolean
  sourceRow?: boolean
  serviceId?: boolean
  provider?: boolean
  module?: boolean
  status?: boolean
  cost?: boolean
  balanceRefund?: boolean
  subjectBody?: boolean
  subjectBodyText?: boolean
  result?: boolean
  error?: boolean
  idempotencyKey?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.Check$batchArgs<ExtArgs>
}, ExtArgs["result"]["check"]>

export type CheckSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  batchId?: boolean
  batchPosition?: boolean
  sourceRow?: boolean
  serviceId?: boolean
  provider?: boolean
  module?: boolean
  status?: boolean
  cost?: boolean
  balanceRefund?: boolean
  subjectBody?: boolean
  subjectBodyText?: boolean
  result?: boolean
  error?: boolean
  idempotencyKey?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.Check$batchArgs<ExtArgs>
}, ExtArgs["result"]["check"]>

export type CheckSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  batchId?: boolean
  batchPosition?: boolean
  sourceRow?: boolean
  serviceId?: boolean
  provider?: boolean
  module?: boolean
  status?: boolean
  cost?: boolean
  balanceRefund?: boolean
  subjectBody?: boolean
  subjectBodyText?: boolean
  result?: boolean
  error?: boolean
  idempotencyKey?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.Check$batchArgs<ExtArgs>
}, ExtArgs["result"]["check"]>

export type CheckSelectScalar = {
  id?: boolean
  userId?: boolean
  batchId?: boolean
  batchPosition?: boolean
  sourceRow?: boolean
  serviceId?: boolean
  provider?: boolean
  module?: boolean
  status?: boolean
  cost?: boolean
  balanceRefund?: boolean
  subjectBody?: boolean
  subjectBodyText?: boolean
  result?: boolean
  error?: boolean
  idempotencyKey?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completedAt?: boolean
}

export type CheckOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "batchId" | "batchPosition" | "sourceRow" | "serviceId" | "provider" | "module" | "status" | "cost" | "balanceRefund" | "subjectBody" | "subjectBodyText" | "result" | "error" | "idempotencyKey" | "createdAt" | "updatedAt" | "completedAt", ExtArgs["result"]["check"]>
export type CheckInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.Check$batchArgs<ExtArgs>
}
export type CheckIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.Check$batchArgs<ExtArgs>
}
export type CheckIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.Check$batchArgs<ExtArgs>
}

export type $CheckPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Check"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    batch: Prisma.$BatchCheckPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    batchId: string | null
    batchPosition: number | null
    sourceRow: number | null
    serviceId: string | null
    provider: $Enums.CheckProviderEnums
    module: $Enums.CheckModuleEnums
    status: $Enums.CheckStatusEnums
    cost: number
    balanceRefund: boolean
    subjectBody: runtime.JsonValue
    subjectBodyText: string
    result: runtime.JsonValue | null
    error: runtime.JsonValue | null
    idempotencyKey: string
    createdAt: Date
    updatedAt: Date
    completedAt: Date | null
  }, ExtArgs["result"]["check"]>
  composites: {}
}

export type CheckGetPayload<S extends boolean | null | undefined | CheckDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CheckPayload, S>

export type CheckCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CheckFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CheckCountAggregateInputType | true
  }

export interface CheckDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Check'], meta: { name: 'Check' } }
  /**
   * Find zero or one Check that matches the filter.
   * @param {CheckFindUniqueArgs} args - Arguments to find a Check
   * @example
   * // Get one Check
   * const check = await prisma.check.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CheckFindUniqueArgs>(args: Prisma.SelectSubset<T, CheckFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CheckClient<runtime.Types.Result.GetResult<Prisma.$CheckPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Check that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CheckFindUniqueOrThrowArgs} args - Arguments to find a Check
   * @example
   * // Get one Check
   * const check = await prisma.check.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CheckFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CheckFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CheckClient<runtime.Types.Result.GetResult<Prisma.$CheckPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Check that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckFindFirstArgs} args - Arguments to find a Check
   * @example
   * // Get one Check
   * const check = await prisma.check.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CheckFindFirstArgs>(args?: Prisma.SelectSubset<T, CheckFindFirstArgs<ExtArgs>>): Prisma.Prisma__CheckClient<runtime.Types.Result.GetResult<Prisma.$CheckPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Check that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckFindFirstOrThrowArgs} args - Arguments to find a Check
   * @example
   * // Get one Check
   * const check = await prisma.check.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CheckFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CheckFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CheckClient<runtime.Types.Result.GetResult<Prisma.$CheckPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Checks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Checks
   * const checks = await prisma.check.findMany()
   * 
   * // Get first 10 Checks
   * const checks = await prisma.check.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const checkWithIdOnly = await prisma.check.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CheckFindManyArgs>(args?: Prisma.SelectSubset<T, CheckFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Check.
   * @param {CheckCreateArgs} args - Arguments to create a Check.
   * @example
   * // Create one Check
   * const Check = await prisma.check.create({
   *   data: {
   *     // ... data to create a Check
   *   }
   * })
   * 
   */
  create<T extends CheckCreateArgs>(args: Prisma.SelectSubset<T, CheckCreateArgs<ExtArgs>>): Prisma.Prisma__CheckClient<runtime.Types.Result.GetResult<Prisma.$CheckPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Checks.
   * @param {CheckCreateManyArgs} args - Arguments to create many Checks.
   * @example
   * // Create many Checks
   * const check = await prisma.check.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CheckCreateManyArgs>(args?: Prisma.SelectSubset<T, CheckCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Checks and returns the data saved in the database.
   * @param {CheckCreateManyAndReturnArgs} args - Arguments to create many Checks.
   * @example
   * // Create many Checks
   * const check = await prisma.check.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Checks and only return the `id`
   * const checkWithIdOnly = await prisma.check.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CheckCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CheckCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Check.
   * @param {CheckDeleteArgs} args - Arguments to delete one Check.
   * @example
   * // Delete one Check
   * const Check = await prisma.check.delete({
   *   where: {
   *     // ... filter to delete one Check
   *   }
   * })
   * 
   */
  delete<T extends CheckDeleteArgs>(args: Prisma.SelectSubset<T, CheckDeleteArgs<ExtArgs>>): Prisma.Prisma__CheckClient<runtime.Types.Result.GetResult<Prisma.$CheckPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Check.
   * @param {CheckUpdateArgs} args - Arguments to update one Check.
   * @example
   * // Update one Check
   * const check = await prisma.check.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CheckUpdateArgs>(args: Prisma.SelectSubset<T, CheckUpdateArgs<ExtArgs>>): Prisma.Prisma__CheckClient<runtime.Types.Result.GetResult<Prisma.$CheckPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Checks.
   * @param {CheckDeleteManyArgs} args - Arguments to filter Checks to delete.
   * @example
   * // Delete a few Checks
   * const { count } = await prisma.check.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CheckDeleteManyArgs>(args?: Prisma.SelectSubset<T, CheckDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Checks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Checks
   * const check = await prisma.check.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CheckUpdateManyArgs>(args: Prisma.SelectSubset<T, CheckUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Checks and returns the data updated in the database.
   * @param {CheckUpdateManyAndReturnArgs} args - Arguments to update many Checks.
   * @example
   * // Update many Checks
   * const check = await prisma.check.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Checks and only return the `id`
   * const checkWithIdOnly = await prisma.check.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CheckUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CheckUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Check.
   * @param {CheckUpsertArgs} args - Arguments to update or create a Check.
   * @example
   * // Update or create a Check
   * const check = await prisma.check.upsert({
   *   create: {
   *     // ... data to create a Check
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Check we want to update
   *   }
   * })
   */
  upsert<T extends CheckUpsertArgs>(args: Prisma.SelectSubset<T, CheckUpsertArgs<ExtArgs>>): Prisma.Prisma__CheckClient<runtime.Types.Result.GetResult<Prisma.$CheckPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Checks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckCountArgs} args - Arguments to filter Checks to count.
   * @example
   * // Count the number of Checks
   * const count = await prisma.check.count({
   *   where: {
   *     // ... the filter for the Checks we want to count
   *   }
   * })
  **/
  count<T extends CheckCountArgs>(
    args?: Prisma.Subset<T, CheckCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CheckCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Check.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CheckAggregateArgs>(args: Prisma.Subset<T, CheckAggregateArgs>): Prisma.PrismaPromise<GetCheckAggregateType<T>>

  /**
   * Group by Check.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CheckGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CheckGroupByArgs['orderBy'] }
      : { orderBy?: CheckGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CheckGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCheckGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Check model
 */
readonly fields: CheckFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Check.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CheckClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  batch<T extends Prisma.Check$batchArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Check$batchArgs<ExtArgs>>): Prisma.Prisma__BatchCheckClient<runtime.Types.Result.GetResult<Prisma.$BatchCheckPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Check model
 */
export interface CheckFieldRefs {
  readonly id: Prisma.FieldRef<"Check", 'String'>
  readonly userId: Prisma.FieldRef<"Check", 'String'>
  readonly batchId: Prisma.FieldRef<"Check", 'String'>
  readonly batchPosition: Prisma.FieldRef<"Check", 'Int'>
  readonly sourceRow: Prisma.FieldRef<"Check", 'Int'>
  readonly serviceId: Prisma.FieldRef<"Check", 'String'>
  readonly provider: Prisma.FieldRef<"Check", 'CheckProviderEnums'>
  readonly module: Prisma.FieldRef<"Check", 'CheckModuleEnums'>
  readonly status: Prisma.FieldRef<"Check", 'CheckStatusEnums'>
  readonly cost: Prisma.FieldRef<"Check", 'Int'>
  readonly balanceRefund: Prisma.FieldRef<"Check", 'Boolean'>
  readonly subjectBody: Prisma.FieldRef<"Check", 'Json'>
  readonly subjectBodyText: Prisma.FieldRef<"Check", 'String'>
  readonly result: Prisma.FieldRef<"Check", 'Json'>
  readonly error: Prisma.FieldRef<"Check", 'Json'>
  readonly idempotencyKey: Prisma.FieldRef<"Check", 'String'>
  readonly createdAt: Prisma.FieldRef<"Check", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Check", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"Check", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Check findUnique
 */
export type CheckFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckInclude<ExtArgs> | null
  /**
   * Filter, which Check to fetch.
   */
  where: Prisma.CheckWhereUniqueInput
}

/**
 * Check findUniqueOrThrow
 */
export type CheckFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckInclude<ExtArgs> | null
  /**
   * Filter, which Check to fetch.
   */
  where: Prisma.CheckWhereUniqueInput
}

/**
 * Check findFirst
 */
export type CheckFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckInclude<ExtArgs> | null
  /**
   * Filter, which Check to fetch.
   */
  where?: Prisma.CheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checks to fetch.
   */
  orderBy?: Prisma.CheckOrderByWithRelationInput | Prisma.CheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Checks.
   */
  cursor?: Prisma.CheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Checks.
   */
  distinct?: Prisma.CheckScalarFieldEnum | Prisma.CheckScalarFieldEnum[]
}

/**
 * Check findFirstOrThrow
 */
export type CheckFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckInclude<ExtArgs> | null
  /**
   * Filter, which Check to fetch.
   */
  where?: Prisma.CheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checks to fetch.
   */
  orderBy?: Prisma.CheckOrderByWithRelationInput | Prisma.CheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Checks.
   */
  cursor?: Prisma.CheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Checks.
   */
  distinct?: Prisma.CheckScalarFieldEnum | Prisma.CheckScalarFieldEnum[]
}

/**
 * Check findMany
 */
export type CheckFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckInclude<ExtArgs> | null
  /**
   * Filter, which Checks to fetch.
   */
  where?: Prisma.CheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checks to fetch.
   */
  orderBy?: Prisma.CheckOrderByWithRelationInput | Prisma.CheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Checks.
   */
  cursor?: Prisma.CheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checks.
   */
  skip?: number
  distinct?: Prisma.CheckScalarFieldEnum | Prisma.CheckScalarFieldEnum[]
}

/**
 * Check create
 */
export type CheckCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckInclude<ExtArgs> | null
  /**
   * The data needed to create a Check.
   */
  data: Prisma.XOR<Prisma.CheckCreateInput, Prisma.CheckUncheckedCreateInput>
}

/**
 * Check createMany
 */
export type CheckCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Checks.
   */
  data: Prisma.CheckCreateManyInput | Prisma.CheckCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Check createManyAndReturn
 */
export type CheckCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * The data used to create many Checks.
   */
  data: Prisma.CheckCreateManyInput | Prisma.CheckCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Check update
 */
export type CheckUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckInclude<ExtArgs> | null
  /**
   * The data needed to update a Check.
   */
  data: Prisma.XOR<Prisma.CheckUpdateInput, Prisma.CheckUncheckedUpdateInput>
  /**
   * Choose, which Check to update.
   */
  where: Prisma.CheckWhereUniqueInput
}

/**
 * Check updateMany
 */
export type CheckUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Checks.
   */
  data: Prisma.XOR<Prisma.CheckUpdateManyMutationInput, Prisma.CheckUncheckedUpdateManyInput>
  /**
   * Filter which Checks to update
   */
  where?: Prisma.CheckWhereInput
  /**
   * Limit how many Checks to update.
   */
  limit?: number
}

/**
 * Check updateManyAndReturn
 */
export type CheckUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * The data used to update Checks.
   */
  data: Prisma.XOR<Prisma.CheckUpdateManyMutationInput, Prisma.CheckUncheckedUpdateManyInput>
  /**
   * Filter which Checks to update
   */
  where?: Prisma.CheckWhereInput
  /**
   * Limit how many Checks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Check upsert
 */
export type CheckUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckInclude<ExtArgs> | null
  /**
   * The filter to search for the Check to update in case it exists.
   */
  where: Prisma.CheckWhereUniqueInput
  /**
   * In case the Check found by the `where` argument doesn't exist, create a new Check with this data.
   */
  create: Prisma.XOR<Prisma.CheckCreateInput, Prisma.CheckUncheckedCreateInput>
  /**
   * In case the Check was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CheckUpdateInput, Prisma.CheckUncheckedUpdateInput>
}

/**
 * Check delete
 */
export type CheckDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckInclude<ExtArgs> | null
  /**
   * Filter which Check to delete.
   */
  where: Prisma.CheckWhereUniqueInput
}

/**
 * Check deleteMany
 */
export type CheckDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Checks to delete
   */
  where?: Prisma.CheckWhereInput
  /**
   * Limit how many Checks to delete.
   */
  limit?: number
}

/**
 * Check.batch
 */
export type Check$batchArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCheck
   */
  select?: Prisma.BatchCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BatchCheck
   */
  omit?: Prisma.BatchCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchCheckInclude<ExtArgs> | null
  where?: Prisma.BatchCheckWhereInput
}

/**
 * Check without action
 */
export type CheckDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Check
   */
  select?: Prisma.CheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Check
   */
  omit?: Prisma.CheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckInclude<ExtArgs> | null
}
