
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FeedbackRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FeedbackRequest
 * 
 */
export type FeedbackRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$FeedbackRequestPayload>

export type AggregateFeedbackRequest = {
  _count: FeedbackRequestCountAggregateOutputType | null
  _avg: FeedbackRequestAvgAggregateOutputType | null
  _sum: FeedbackRequestSumAggregateOutputType | null
  _min: FeedbackRequestMinAggregateOutputType | null
  _max: FeedbackRequestMaxAggregateOutputType | null
}

export type FeedbackRequestAvgAggregateOutputType = {
  attachmentSize: number | null
}

export type FeedbackRequestSumAggregateOutputType = {
  attachmentSize: number | null
}

export type FeedbackRequestMinAggregateOutputType = {
  id: string | null
  name: string | null
  companyName: string | null
  email: string | null
  phone: string | null
  message: string | null
  status: $Enums.FeedbackStatus | null
  attachmentName: string | null
  attachmentMimeType: string | null
  attachmentSize: number | null
  attachmentData: runtime.Bytes | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FeedbackRequestMaxAggregateOutputType = {
  id: string | null
  name: string | null
  companyName: string | null
  email: string | null
  phone: string | null
  message: string | null
  status: $Enums.FeedbackStatus | null
  attachmentName: string | null
  attachmentMimeType: string | null
  attachmentSize: number | null
  attachmentData: runtime.Bytes | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FeedbackRequestCountAggregateOutputType = {
  id: number
  name: number
  companyName: number
  email: number
  phone: number
  message: number
  status: number
  attachmentName: number
  attachmentMimeType: number
  attachmentSize: number
  attachmentData: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FeedbackRequestAvgAggregateInputType = {
  attachmentSize?: true
}

export type FeedbackRequestSumAggregateInputType = {
  attachmentSize?: true
}

export type FeedbackRequestMinAggregateInputType = {
  id?: true
  name?: true
  companyName?: true
  email?: true
  phone?: true
  message?: true
  status?: true
  attachmentName?: true
  attachmentMimeType?: true
  attachmentSize?: true
  attachmentData?: true
  createdAt?: true
  updatedAt?: true
}

export type FeedbackRequestMaxAggregateInputType = {
  id?: true
  name?: true
  companyName?: true
  email?: true
  phone?: true
  message?: true
  status?: true
  attachmentName?: true
  attachmentMimeType?: true
  attachmentSize?: true
  attachmentData?: true
  createdAt?: true
  updatedAt?: true
}

export type FeedbackRequestCountAggregateInputType = {
  id?: true
  name?: true
  companyName?: true
  email?: true
  phone?: true
  message?: true
  status?: true
  attachmentName?: true
  attachmentMimeType?: true
  attachmentSize?: true
  attachmentData?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FeedbackRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FeedbackRequest to aggregate.
   */
  where?: Prisma.FeedbackRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeedbackRequests to fetch.
   */
  orderBy?: Prisma.FeedbackRequestOrderByWithRelationInput | Prisma.FeedbackRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FeedbackRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeedbackRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeedbackRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FeedbackRequests
  **/
  _count?: true | FeedbackRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FeedbackRequestAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FeedbackRequestSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FeedbackRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FeedbackRequestMaxAggregateInputType
}

export type GetFeedbackRequestAggregateType<T extends FeedbackRequestAggregateArgs> = {
      [P in keyof T & keyof AggregateFeedbackRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFeedbackRequest[P]>
    : Prisma.GetScalarType<T[P], AggregateFeedbackRequest[P]>
}




export type FeedbackRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FeedbackRequestWhereInput
  orderBy?: Prisma.FeedbackRequestOrderByWithAggregationInput | Prisma.FeedbackRequestOrderByWithAggregationInput[]
  by: Prisma.FeedbackRequestScalarFieldEnum[] | Prisma.FeedbackRequestScalarFieldEnum
  having?: Prisma.FeedbackRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FeedbackRequestCountAggregateInputType | true
  _avg?: FeedbackRequestAvgAggregateInputType
  _sum?: FeedbackRequestSumAggregateInputType
  _min?: FeedbackRequestMinAggregateInputType
  _max?: FeedbackRequestMaxAggregateInputType
}

export type FeedbackRequestGroupByOutputType = {
  id: string
  name: string
  companyName: string
  email: string
  phone: string
  message: string
  status: $Enums.FeedbackStatus
  attachmentName: string | null
  attachmentMimeType: string | null
  attachmentSize: number | null
  attachmentData: runtime.Bytes | null
  createdAt: Date
  updatedAt: Date
  _count: FeedbackRequestCountAggregateOutputType | null
  _avg: FeedbackRequestAvgAggregateOutputType | null
  _sum: FeedbackRequestSumAggregateOutputType | null
  _min: FeedbackRequestMinAggregateOutputType | null
  _max: FeedbackRequestMaxAggregateOutputType | null
}

type GetFeedbackRequestGroupByPayload<T extends FeedbackRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FeedbackRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FeedbackRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FeedbackRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FeedbackRequestGroupByOutputType[P]>
      }
    >
  >



export type FeedbackRequestWhereInput = {
  AND?: Prisma.FeedbackRequestWhereInput | Prisma.FeedbackRequestWhereInput[]
  OR?: Prisma.FeedbackRequestWhereInput[]
  NOT?: Prisma.FeedbackRequestWhereInput | Prisma.FeedbackRequestWhereInput[]
  id?: Prisma.StringFilter<"FeedbackRequest"> | string
  name?: Prisma.StringFilter<"FeedbackRequest"> | string
  companyName?: Prisma.StringFilter<"FeedbackRequest"> | string
  email?: Prisma.StringFilter<"FeedbackRequest"> | string
  phone?: Prisma.StringFilter<"FeedbackRequest"> | string
  message?: Prisma.StringFilter<"FeedbackRequest"> | string
  status?: Prisma.EnumFeedbackStatusFilter<"FeedbackRequest"> | $Enums.FeedbackStatus
  attachmentName?: Prisma.StringNullableFilter<"FeedbackRequest"> | string | null
  attachmentMimeType?: Prisma.StringNullableFilter<"FeedbackRequest"> | string | null
  attachmentSize?: Prisma.IntNullableFilter<"FeedbackRequest"> | number | null
  attachmentData?: Prisma.BytesNullableFilter<"FeedbackRequest"> | runtime.Bytes | null
  createdAt?: Prisma.DateTimeFilter<"FeedbackRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FeedbackRequest"> | Date | string
}

export type FeedbackRequestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attachmentName?: Prisma.SortOrderInput | Prisma.SortOrder
  attachmentMimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  attachmentSize?: Prisma.SortOrderInput | Prisma.SortOrder
  attachmentData?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FeedbackRequestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FeedbackRequestWhereInput | Prisma.FeedbackRequestWhereInput[]
  OR?: Prisma.FeedbackRequestWhereInput[]
  NOT?: Prisma.FeedbackRequestWhereInput | Prisma.FeedbackRequestWhereInput[]
  name?: Prisma.StringFilter<"FeedbackRequest"> | string
  companyName?: Prisma.StringFilter<"FeedbackRequest"> | string
  email?: Prisma.StringFilter<"FeedbackRequest"> | string
  phone?: Prisma.StringFilter<"FeedbackRequest"> | string
  message?: Prisma.StringFilter<"FeedbackRequest"> | string
  status?: Prisma.EnumFeedbackStatusFilter<"FeedbackRequest"> | $Enums.FeedbackStatus
  attachmentName?: Prisma.StringNullableFilter<"FeedbackRequest"> | string | null
  attachmentMimeType?: Prisma.StringNullableFilter<"FeedbackRequest"> | string | null
  attachmentSize?: Prisma.IntNullableFilter<"FeedbackRequest"> | number | null
  attachmentData?: Prisma.BytesNullableFilter<"FeedbackRequest"> | runtime.Bytes | null
  createdAt?: Prisma.DateTimeFilter<"FeedbackRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FeedbackRequest"> | Date | string
}, "id">

export type FeedbackRequestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attachmentName?: Prisma.SortOrderInput | Prisma.SortOrder
  attachmentMimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  attachmentSize?: Prisma.SortOrderInput | Prisma.SortOrder
  attachmentData?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FeedbackRequestCountOrderByAggregateInput
  _avg?: Prisma.FeedbackRequestAvgOrderByAggregateInput
  _max?: Prisma.FeedbackRequestMaxOrderByAggregateInput
  _min?: Prisma.FeedbackRequestMinOrderByAggregateInput
  _sum?: Prisma.FeedbackRequestSumOrderByAggregateInput
}

export type FeedbackRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.FeedbackRequestScalarWhereWithAggregatesInput | Prisma.FeedbackRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.FeedbackRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FeedbackRequestScalarWhereWithAggregatesInput | Prisma.FeedbackRequestScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FeedbackRequest"> | string
  name?: Prisma.StringWithAggregatesFilter<"FeedbackRequest"> | string
  companyName?: Prisma.StringWithAggregatesFilter<"FeedbackRequest"> | string
  email?: Prisma.StringWithAggregatesFilter<"FeedbackRequest"> | string
  phone?: Prisma.StringWithAggregatesFilter<"FeedbackRequest"> | string
  message?: Prisma.StringWithAggregatesFilter<"FeedbackRequest"> | string
  status?: Prisma.EnumFeedbackStatusWithAggregatesFilter<"FeedbackRequest"> | $Enums.FeedbackStatus
  attachmentName?: Prisma.StringNullableWithAggregatesFilter<"FeedbackRequest"> | string | null
  attachmentMimeType?: Prisma.StringNullableWithAggregatesFilter<"FeedbackRequest"> | string | null
  attachmentSize?: Prisma.IntNullableWithAggregatesFilter<"FeedbackRequest"> | number | null
  attachmentData?: Prisma.BytesNullableWithAggregatesFilter<"FeedbackRequest"> | runtime.Bytes | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FeedbackRequest"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FeedbackRequest"> | Date | string
}

export type FeedbackRequestCreateInput = {
  id?: string
  name: string
  companyName: string
  email: string
  phone: string
  message: string
  status?: $Enums.FeedbackStatus
  attachmentName?: string | null
  attachmentMimeType?: string | null
  attachmentSize?: number | null
  attachmentData?: runtime.Bytes | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FeedbackRequestUncheckedCreateInput = {
  id?: string
  name: string
  companyName: string
  email: string
  phone: string
  message: string
  status?: $Enums.FeedbackStatus
  attachmentName?: string | null
  attachmentMimeType?: string | null
  attachmentSize?: number | null
  attachmentData?: runtime.Bytes | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FeedbackRequestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumFeedbackStatusFieldUpdateOperationsInput | $Enums.FeedbackStatus
  attachmentName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentMimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  attachmentData?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeedbackRequestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumFeedbackStatusFieldUpdateOperationsInput | $Enums.FeedbackStatus
  attachmentName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentMimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  attachmentData?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeedbackRequestCreateManyInput = {
  id?: string
  name: string
  companyName: string
  email: string
  phone: string
  message: string
  status?: $Enums.FeedbackStatus
  attachmentName?: string | null
  attachmentMimeType?: string | null
  attachmentSize?: number | null
  attachmentData?: runtime.Bytes | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FeedbackRequestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumFeedbackStatusFieldUpdateOperationsInput | $Enums.FeedbackStatus
  attachmentName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentMimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  attachmentData?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeedbackRequestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumFeedbackStatusFieldUpdateOperationsInput | $Enums.FeedbackStatus
  attachmentName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentMimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  attachmentData?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeedbackRequestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attachmentName?: Prisma.SortOrder
  attachmentMimeType?: Prisma.SortOrder
  attachmentSize?: Prisma.SortOrder
  attachmentData?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FeedbackRequestAvgOrderByAggregateInput = {
  attachmentSize?: Prisma.SortOrder
}

export type FeedbackRequestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attachmentName?: Prisma.SortOrder
  attachmentMimeType?: Prisma.SortOrder
  attachmentSize?: Prisma.SortOrder
  attachmentData?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FeedbackRequestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attachmentName?: Prisma.SortOrder
  attachmentMimeType?: Prisma.SortOrder
  attachmentSize?: Prisma.SortOrder
  attachmentData?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FeedbackRequestSumOrderByAggregateInput = {
  attachmentSize?: Prisma.SortOrder
}

export type EnumFeedbackStatusFieldUpdateOperationsInput = {
  set?: $Enums.FeedbackStatus
}

export type NullableBytesFieldUpdateOperationsInput = {
  set?: runtime.Bytes | null
}



export type FeedbackRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  companyName?: boolean
  email?: boolean
  phone?: boolean
  message?: boolean
  status?: boolean
  attachmentName?: boolean
  attachmentMimeType?: boolean
  attachmentSize?: boolean
  attachmentData?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["feedbackRequest"]>

export type FeedbackRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  companyName?: boolean
  email?: boolean
  phone?: boolean
  message?: boolean
  status?: boolean
  attachmentName?: boolean
  attachmentMimeType?: boolean
  attachmentSize?: boolean
  attachmentData?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["feedbackRequest"]>

export type FeedbackRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  companyName?: boolean
  email?: boolean
  phone?: boolean
  message?: boolean
  status?: boolean
  attachmentName?: boolean
  attachmentMimeType?: boolean
  attachmentSize?: boolean
  attachmentData?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["feedbackRequest"]>

export type FeedbackRequestSelectScalar = {
  id?: boolean
  name?: boolean
  companyName?: boolean
  email?: boolean
  phone?: boolean
  message?: boolean
  status?: boolean
  attachmentName?: boolean
  attachmentMimeType?: boolean
  attachmentSize?: boolean
  attachmentData?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FeedbackRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "companyName" | "email" | "phone" | "message" | "status" | "attachmentName" | "attachmentMimeType" | "attachmentSize" | "attachmentData" | "createdAt" | "updatedAt", ExtArgs["result"]["feedbackRequest"]>

export type $FeedbackRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FeedbackRequest"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    companyName: string
    email: string
    phone: string
    message: string
    status: $Enums.FeedbackStatus
    attachmentName: string | null
    attachmentMimeType: string | null
    attachmentSize: number | null
    attachmentData: runtime.Bytes | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["feedbackRequest"]>
  composites: {}
}

export type FeedbackRequestGetPayload<S extends boolean | null | undefined | FeedbackRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FeedbackRequestPayload, S>

export type FeedbackRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FeedbackRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FeedbackRequestCountAggregateInputType | true
  }

export interface FeedbackRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FeedbackRequest'], meta: { name: 'FeedbackRequest' } }
  /**
   * Find zero or one FeedbackRequest that matches the filter.
   * @param {FeedbackRequestFindUniqueArgs} args - Arguments to find a FeedbackRequest
   * @example
   * // Get one FeedbackRequest
   * const feedbackRequest = await prisma.feedbackRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FeedbackRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, FeedbackRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FeedbackRequestClient<runtime.Types.Result.GetResult<Prisma.$FeedbackRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FeedbackRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FeedbackRequestFindUniqueOrThrowArgs} args - Arguments to find a FeedbackRequest
   * @example
   * // Get one FeedbackRequest
   * const feedbackRequest = await prisma.feedbackRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FeedbackRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FeedbackRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FeedbackRequestClient<runtime.Types.Result.GetResult<Prisma.$FeedbackRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FeedbackRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackRequestFindFirstArgs} args - Arguments to find a FeedbackRequest
   * @example
   * // Get one FeedbackRequest
   * const feedbackRequest = await prisma.feedbackRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FeedbackRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, FeedbackRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__FeedbackRequestClient<runtime.Types.Result.GetResult<Prisma.$FeedbackRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FeedbackRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackRequestFindFirstOrThrowArgs} args - Arguments to find a FeedbackRequest
   * @example
   * // Get one FeedbackRequest
   * const feedbackRequest = await prisma.feedbackRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FeedbackRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FeedbackRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FeedbackRequestClient<runtime.Types.Result.GetResult<Prisma.$FeedbackRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FeedbackRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FeedbackRequests
   * const feedbackRequests = await prisma.feedbackRequest.findMany()
   * 
   * // Get first 10 FeedbackRequests
   * const feedbackRequests = await prisma.feedbackRequest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const feedbackRequestWithIdOnly = await prisma.feedbackRequest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FeedbackRequestFindManyArgs>(args?: Prisma.SelectSubset<T, FeedbackRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeedbackRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FeedbackRequest.
   * @param {FeedbackRequestCreateArgs} args - Arguments to create a FeedbackRequest.
   * @example
   * // Create one FeedbackRequest
   * const FeedbackRequest = await prisma.feedbackRequest.create({
   *   data: {
   *     // ... data to create a FeedbackRequest
   *   }
   * })
   * 
   */
  create<T extends FeedbackRequestCreateArgs>(args: Prisma.SelectSubset<T, FeedbackRequestCreateArgs<ExtArgs>>): Prisma.Prisma__FeedbackRequestClient<runtime.Types.Result.GetResult<Prisma.$FeedbackRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FeedbackRequests.
   * @param {FeedbackRequestCreateManyArgs} args - Arguments to create many FeedbackRequests.
   * @example
   * // Create many FeedbackRequests
   * const feedbackRequest = await prisma.feedbackRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FeedbackRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, FeedbackRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FeedbackRequests and returns the data saved in the database.
   * @param {FeedbackRequestCreateManyAndReturnArgs} args - Arguments to create many FeedbackRequests.
   * @example
   * // Create many FeedbackRequests
   * const feedbackRequest = await prisma.feedbackRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FeedbackRequests and only return the `id`
   * const feedbackRequestWithIdOnly = await prisma.feedbackRequest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FeedbackRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FeedbackRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeedbackRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FeedbackRequest.
   * @param {FeedbackRequestDeleteArgs} args - Arguments to delete one FeedbackRequest.
   * @example
   * // Delete one FeedbackRequest
   * const FeedbackRequest = await prisma.feedbackRequest.delete({
   *   where: {
   *     // ... filter to delete one FeedbackRequest
   *   }
   * })
   * 
   */
  delete<T extends FeedbackRequestDeleteArgs>(args: Prisma.SelectSubset<T, FeedbackRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__FeedbackRequestClient<runtime.Types.Result.GetResult<Prisma.$FeedbackRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FeedbackRequest.
   * @param {FeedbackRequestUpdateArgs} args - Arguments to update one FeedbackRequest.
   * @example
   * // Update one FeedbackRequest
   * const feedbackRequest = await prisma.feedbackRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FeedbackRequestUpdateArgs>(args: Prisma.SelectSubset<T, FeedbackRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__FeedbackRequestClient<runtime.Types.Result.GetResult<Prisma.$FeedbackRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FeedbackRequests.
   * @param {FeedbackRequestDeleteManyArgs} args - Arguments to filter FeedbackRequests to delete.
   * @example
   * // Delete a few FeedbackRequests
   * const { count } = await prisma.feedbackRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FeedbackRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, FeedbackRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FeedbackRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FeedbackRequests
   * const feedbackRequest = await prisma.feedbackRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FeedbackRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, FeedbackRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FeedbackRequests and returns the data updated in the database.
   * @param {FeedbackRequestUpdateManyAndReturnArgs} args - Arguments to update many FeedbackRequests.
   * @example
   * // Update many FeedbackRequests
   * const feedbackRequest = await prisma.feedbackRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FeedbackRequests and only return the `id`
   * const feedbackRequestWithIdOnly = await prisma.feedbackRequest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FeedbackRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FeedbackRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeedbackRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FeedbackRequest.
   * @param {FeedbackRequestUpsertArgs} args - Arguments to update or create a FeedbackRequest.
   * @example
   * // Update or create a FeedbackRequest
   * const feedbackRequest = await prisma.feedbackRequest.upsert({
   *   create: {
   *     // ... data to create a FeedbackRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FeedbackRequest we want to update
   *   }
   * })
   */
  upsert<T extends FeedbackRequestUpsertArgs>(args: Prisma.SelectSubset<T, FeedbackRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__FeedbackRequestClient<runtime.Types.Result.GetResult<Prisma.$FeedbackRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FeedbackRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackRequestCountArgs} args - Arguments to filter FeedbackRequests to count.
   * @example
   * // Count the number of FeedbackRequests
   * const count = await prisma.feedbackRequest.count({
   *   where: {
   *     // ... the filter for the FeedbackRequests we want to count
   *   }
   * })
  **/
  count<T extends FeedbackRequestCountArgs>(
    args?: Prisma.Subset<T, FeedbackRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FeedbackRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FeedbackRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FeedbackRequestAggregateArgs>(args: Prisma.Subset<T, FeedbackRequestAggregateArgs>): Prisma.PrismaPromise<GetFeedbackRequestAggregateType<T>>

  /**
   * Group by FeedbackRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FeedbackRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FeedbackRequestGroupByArgs['orderBy'] }
      : { orderBy?: FeedbackRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FeedbackRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFeedbackRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FeedbackRequest model
 */
readonly fields: FeedbackRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FeedbackRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FeedbackRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FeedbackRequest model
 */
export interface FeedbackRequestFieldRefs {
  readonly id: Prisma.FieldRef<"FeedbackRequest", 'String'>
  readonly name: Prisma.FieldRef<"FeedbackRequest", 'String'>
  readonly companyName: Prisma.FieldRef<"FeedbackRequest", 'String'>
  readonly email: Prisma.FieldRef<"FeedbackRequest", 'String'>
  readonly phone: Prisma.FieldRef<"FeedbackRequest", 'String'>
  readonly message: Prisma.FieldRef<"FeedbackRequest", 'String'>
  readonly status: Prisma.FieldRef<"FeedbackRequest", 'FeedbackStatus'>
  readonly attachmentName: Prisma.FieldRef<"FeedbackRequest", 'String'>
  readonly attachmentMimeType: Prisma.FieldRef<"FeedbackRequest", 'String'>
  readonly attachmentSize: Prisma.FieldRef<"FeedbackRequest", 'Int'>
  readonly attachmentData: Prisma.FieldRef<"FeedbackRequest", 'Bytes'>
  readonly createdAt: Prisma.FieldRef<"FeedbackRequest", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FeedbackRequest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FeedbackRequest findUnique
 */
export type FeedbackRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackRequest
   */
  select?: Prisma.FeedbackRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackRequest
   */
  omit?: Prisma.FeedbackRequestOmit<ExtArgs> | null
  /**
   * Filter, which FeedbackRequest to fetch.
   */
  where: Prisma.FeedbackRequestWhereUniqueInput
}

/**
 * FeedbackRequest findUniqueOrThrow
 */
export type FeedbackRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackRequest
   */
  select?: Prisma.FeedbackRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackRequest
   */
  omit?: Prisma.FeedbackRequestOmit<ExtArgs> | null
  /**
   * Filter, which FeedbackRequest to fetch.
   */
  where: Prisma.FeedbackRequestWhereUniqueInput
}

/**
 * FeedbackRequest findFirst
 */
export type FeedbackRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackRequest
   */
  select?: Prisma.FeedbackRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackRequest
   */
  omit?: Prisma.FeedbackRequestOmit<ExtArgs> | null
  /**
   * Filter, which FeedbackRequest to fetch.
   */
  where?: Prisma.FeedbackRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeedbackRequests to fetch.
   */
  orderBy?: Prisma.FeedbackRequestOrderByWithRelationInput | Prisma.FeedbackRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FeedbackRequests.
   */
  cursor?: Prisma.FeedbackRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeedbackRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeedbackRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FeedbackRequests.
   */
  distinct?: Prisma.FeedbackRequestScalarFieldEnum | Prisma.FeedbackRequestScalarFieldEnum[]
}

/**
 * FeedbackRequest findFirstOrThrow
 */
export type FeedbackRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackRequest
   */
  select?: Prisma.FeedbackRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackRequest
   */
  omit?: Prisma.FeedbackRequestOmit<ExtArgs> | null
  /**
   * Filter, which FeedbackRequest to fetch.
   */
  where?: Prisma.FeedbackRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeedbackRequests to fetch.
   */
  orderBy?: Prisma.FeedbackRequestOrderByWithRelationInput | Prisma.FeedbackRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FeedbackRequests.
   */
  cursor?: Prisma.FeedbackRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeedbackRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeedbackRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FeedbackRequests.
   */
  distinct?: Prisma.FeedbackRequestScalarFieldEnum | Prisma.FeedbackRequestScalarFieldEnum[]
}

/**
 * FeedbackRequest findMany
 */
export type FeedbackRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackRequest
   */
  select?: Prisma.FeedbackRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackRequest
   */
  omit?: Prisma.FeedbackRequestOmit<ExtArgs> | null
  /**
   * Filter, which FeedbackRequests to fetch.
   */
  where?: Prisma.FeedbackRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeedbackRequests to fetch.
   */
  orderBy?: Prisma.FeedbackRequestOrderByWithRelationInput | Prisma.FeedbackRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FeedbackRequests.
   */
  cursor?: Prisma.FeedbackRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeedbackRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeedbackRequests.
   */
  skip?: number
  distinct?: Prisma.FeedbackRequestScalarFieldEnum | Prisma.FeedbackRequestScalarFieldEnum[]
}

/**
 * FeedbackRequest create
 */
export type FeedbackRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackRequest
   */
  select?: Prisma.FeedbackRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackRequest
   */
  omit?: Prisma.FeedbackRequestOmit<ExtArgs> | null
  /**
   * The data needed to create a FeedbackRequest.
   */
  data: Prisma.XOR<Prisma.FeedbackRequestCreateInput, Prisma.FeedbackRequestUncheckedCreateInput>
}

/**
 * FeedbackRequest createMany
 */
export type FeedbackRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FeedbackRequests.
   */
  data: Prisma.FeedbackRequestCreateManyInput | Prisma.FeedbackRequestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FeedbackRequest createManyAndReturn
 */
export type FeedbackRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackRequest
   */
  select?: Prisma.FeedbackRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackRequest
   */
  omit?: Prisma.FeedbackRequestOmit<ExtArgs> | null
  /**
   * The data used to create many FeedbackRequests.
   */
  data: Prisma.FeedbackRequestCreateManyInput | Prisma.FeedbackRequestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FeedbackRequest update
 */
export type FeedbackRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackRequest
   */
  select?: Prisma.FeedbackRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackRequest
   */
  omit?: Prisma.FeedbackRequestOmit<ExtArgs> | null
  /**
   * The data needed to update a FeedbackRequest.
   */
  data: Prisma.XOR<Prisma.FeedbackRequestUpdateInput, Prisma.FeedbackRequestUncheckedUpdateInput>
  /**
   * Choose, which FeedbackRequest to update.
   */
  where: Prisma.FeedbackRequestWhereUniqueInput
}

/**
 * FeedbackRequest updateMany
 */
export type FeedbackRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FeedbackRequests.
   */
  data: Prisma.XOR<Prisma.FeedbackRequestUpdateManyMutationInput, Prisma.FeedbackRequestUncheckedUpdateManyInput>
  /**
   * Filter which FeedbackRequests to update
   */
  where?: Prisma.FeedbackRequestWhereInput
  /**
   * Limit how many FeedbackRequests to update.
   */
  limit?: number
}

/**
 * FeedbackRequest updateManyAndReturn
 */
export type FeedbackRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackRequest
   */
  select?: Prisma.FeedbackRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackRequest
   */
  omit?: Prisma.FeedbackRequestOmit<ExtArgs> | null
  /**
   * The data used to update FeedbackRequests.
   */
  data: Prisma.XOR<Prisma.FeedbackRequestUpdateManyMutationInput, Prisma.FeedbackRequestUncheckedUpdateManyInput>
  /**
   * Filter which FeedbackRequests to update
   */
  where?: Prisma.FeedbackRequestWhereInput
  /**
   * Limit how many FeedbackRequests to update.
   */
  limit?: number
}

/**
 * FeedbackRequest upsert
 */
export type FeedbackRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackRequest
   */
  select?: Prisma.FeedbackRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackRequest
   */
  omit?: Prisma.FeedbackRequestOmit<ExtArgs> | null
  /**
   * The filter to search for the FeedbackRequest to update in case it exists.
   */
  where: Prisma.FeedbackRequestWhereUniqueInput
  /**
   * In case the FeedbackRequest found by the `where` argument doesn't exist, create a new FeedbackRequest with this data.
   */
  create: Prisma.XOR<Prisma.FeedbackRequestCreateInput, Prisma.FeedbackRequestUncheckedCreateInput>
  /**
   * In case the FeedbackRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FeedbackRequestUpdateInput, Prisma.FeedbackRequestUncheckedUpdateInput>
}

/**
 * FeedbackRequest delete
 */
export type FeedbackRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackRequest
   */
  select?: Prisma.FeedbackRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackRequest
   */
  omit?: Prisma.FeedbackRequestOmit<ExtArgs> | null
  /**
   * Filter which FeedbackRequest to delete.
   */
  where: Prisma.FeedbackRequestWhereUniqueInput
}

/**
 * FeedbackRequest deleteMany
 */
export type FeedbackRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FeedbackRequests to delete
   */
  where?: Prisma.FeedbackRequestWhereInput
  /**
   * Limit how many FeedbackRequests to delete.
   */
  limit?: number
}

/**
 * FeedbackRequest without action
 */
export type FeedbackRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackRequest
   */
  select?: Prisma.FeedbackRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackRequest
   */
  omit?: Prisma.FeedbackRequestOmit<ExtArgs> | null
}
