
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserCheckPrice` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model UserCheckPrice
 * 
 */
export type UserCheckPriceModel = runtime.Types.Result.DefaultSelection<Prisma.$UserCheckPricePayload>

export type AggregateUserCheckPrice = {
  _count: UserCheckPriceCountAggregateOutputType | null
  _avg: UserCheckPriceAvgAggregateOutputType | null
  _sum: UserCheckPriceSumAggregateOutputType | null
  _min: UserCheckPriceMinAggregateOutputType | null
  _max: UserCheckPriceMaxAggregateOutputType | null
}

export type UserCheckPriceAvgAggregateOutputType = {
  price: number | null
}

export type UserCheckPriceSumAggregateOutputType = {
  price: number | null
}

export type UserCheckPriceMinAggregateOutputType = {
  userId: string | null
  module: $Enums.CheckModuleEnums | null
  price: number | null
}

export type UserCheckPriceMaxAggregateOutputType = {
  userId: string | null
  module: $Enums.CheckModuleEnums | null
  price: number | null
}

export type UserCheckPriceCountAggregateOutputType = {
  userId: number
  module: number
  price: number
  _all: number
}


export type UserCheckPriceAvgAggregateInputType = {
  price?: true
}

export type UserCheckPriceSumAggregateInputType = {
  price?: true
}

export type UserCheckPriceMinAggregateInputType = {
  userId?: true
  module?: true
  price?: true
}

export type UserCheckPriceMaxAggregateInputType = {
  userId?: true
  module?: true
  price?: true
}

export type UserCheckPriceCountAggregateInputType = {
  userId?: true
  module?: true
  price?: true
  _all?: true
}

export type UserCheckPriceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserCheckPrice to aggregate.
   */
  where?: Prisma.UserCheckPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserCheckPrices to fetch.
   */
  orderBy?: Prisma.UserCheckPriceOrderByWithRelationInput | Prisma.UserCheckPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserCheckPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserCheckPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserCheckPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserCheckPrices
  **/
  _count?: true | UserCheckPriceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserCheckPriceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserCheckPriceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserCheckPriceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserCheckPriceMaxAggregateInputType
}

export type GetUserCheckPriceAggregateType<T extends UserCheckPriceAggregateArgs> = {
      [P in keyof T & keyof AggregateUserCheckPrice]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserCheckPrice[P]>
    : Prisma.GetScalarType<T[P], AggregateUserCheckPrice[P]>
}




export type UserCheckPriceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserCheckPriceWhereInput
  orderBy?: Prisma.UserCheckPriceOrderByWithAggregationInput | Prisma.UserCheckPriceOrderByWithAggregationInput[]
  by: Prisma.UserCheckPriceScalarFieldEnum[] | Prisma.UserCheckPriceScalarFieldEnum
  having?: Prisma.UserCheckPriceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCheckPriceCountAggregateInputType | true
  _avg?: UserCheckPriceAvgAggregateInputType
  _sum?: UserCheckPriceSumAggregateInputType
  _min?: UserCheckPriceMinAggregateInputType
  _max?: UserCheckPriceMaxAggregateInputType
}

export type UserCheckPriceGroupByOutputType = {
  userId: string
  module: $Enums.CheckModuleEnums
  price: number
  _count: UserCheckPriceCountAggregateOutputType | null
  _avg: UserCheckPriceAvgAggregateOutputType | null
  _sum: UserCheckPriceSumAggregateOutputType | null
  _min: UserCheckPriceMinAggregateOutputType | null
  _max: UserCheckPriceMaxAggregateOutputType | null
}

type GetUserCheckPriceGroupByPayload<T extends UserCheckPriceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserCheckPriceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserCheckPriceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserCheckPriceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserCheckPriceGroupByOutputType[P]>
      }
    >
  >



export type UserCheckPriceWhereInput = {
  AND?: Prisma.UserCheckPriceWhereInput | Prisma.UserCheckPriceWhereInput[]
  OR?: Prisma.UserCheckPriceWhereInput[]
  NOT?: Prisma.UserCheckPriceWhereInput | Prisma.UserCheckPriceWhereInput[]
  userId?: Prisma.StringFilter<"UserCheckPrice"> | string
  module?: Prisma.EnumCheckModuleEnumsFilter<"UserCheckPrice"> | $Enums.CheckModuleEnums
  price?: Prisma.IntFilter<"UserCheckPrice"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserCheckPriceOrderByWithRelationInput = {
  userId?: Prisma.SortOrder
  module?: Prisma.SortOrder
  price?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type UserCheckPriceWhereUniqueInput = Prisma.AtLeast<{
  userId_module?: Prisma.UserCheckPriceUserIdModuleCompoundUniqueInput
  AND?: Prisma.UserCheckPriceWhereInput | Prisma.UserCheckPriceWhereInput[]
  OR?: Prisma.UserCheckPriceWhereInput[]
  NOT?: Prisma.UserCheckPriceWhereInput | Prisma.UserCheckPriceWhereInput[]
  userId?: Prisma.StringFilter<"UserCheckPrice"> | string
  module?: Prisma.EnumCheckModuleEnumsFilter<"UserCheckPrice"> | $Enums.CheckModuleEnums
  price?: Prisma.IntFilter<"UserCheckPrice"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "userId_module">

export type UserCheckPriceOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder
  module?: Prisma.SortOrder
  price?: Prisma.SortOrder
  _count?: Prisma.UserCheckPriceCountOrderByAggregateInput
  _avg?: Prisma.UserCheckPriceAvgOrderByAggregateInput
  _max?: Prisma.UserCheckPriceMaxOrderByAggregateInput
  _min?: Prisma.UserCheckPriceMinOrderByAggregateInput
  _sum?: Prisma.UserCheckPriceSumOrderByAggregateInput
}

export type UserCheckPriceScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserCheckPriceScalarWhereWithAggregatesInput | Prisma.UserCheckPriceScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserCheckPriceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserCheckPriceScalarWhereWithAggregatesInput | Prisma.UserCheckPriceScalarWhereWithAggregatesInput[]
  userId?: Prisma.StringWithAggregatesFilter<"UserCheckPrice"> | string
  module?: Prisma.EnumCheckModuleEnumsWithAggregatesFilter<"UserCheckPrice"> | $Enums.CheckModuleEnums
  price?: Prisma.IntWithAggregatesFilter<"UserCheckPrice"> | number
}

export type UserCheckPriceCreateInput = {
  module: $Enums.CheckModuleEnums
  price: number
  user: Prisma.UserCreateNestedOneWithoutCheckPriceOverridesInput
}

export type UserCheckPriceUncheckedCreateInput = {
  userId: string
  module: $Enums.CheckModuleEnums
  price: number
}

export type UserCheckPriceUpdateInput = {
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  price?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutCheckPriceOverridesNestedInput
}

export type UserCheckPriceUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  price?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserCheckPriceCreateManyInput = {
  userId: string
  module: $Enums.CheckModuleEnums
  price: number
}

export type UserCheckPriceUpdateManyMutationInput = {
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  price?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserCheckPriceUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  price?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserCheckPriceListRelationFilter = {
  every?: Prisma.UserCheckPriceWhereInput
  some?: Prisma.UserCheckPriceWhereInput
  none?: Prisma.UserCheckPriceWhereInput
}

export type UserCheckPriceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserCheckPriceUserIdModuleCompoundUniqueInput = {
  userId: string
  module: $Enums.CheckModuleEnums
}

export type UserCheckPriceCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  module?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type UserCheckPriceAvgOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type UserCheckPriceMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  module?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type UserCheckPriceMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  module?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type UserCheckPriceSumOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type UserCheckPriceCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserCheckPriceCreateWithoutUserInput, Prisma.UserCheckPriceUncheckedCreateWithoutUserInput> | Prisma.UserCheckPriceCreateWithoutUserInput[] | Prisma.UserCheckPriceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserCheckPriceCreateOrConnectWithoutUserInput | Prisma.UserCheckPriceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserCheckPriceCreateManyUserInputEnvelope
  connect?: Prisma.UserCheckPriceWhereUniqueInput | Prisma.UserCheckPriceWhereUniqueInput[]
}

export type UserCheckPriceUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserCheckPriceCreateWithoutUserInput, Prisma.UserCheckPriceUncheckedCreateWithoutUserInput> | Prisma.UserCheckPriceCreateWithoutUserInput[] | Prisma.UserCheckPriceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserCheckPriceCreateOrConnectWithoutUserInput | Prisma.UserCheckPriceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserCheckPriceCreateManyUserInputEnvelope
  connect?: Prisma.UserCheckPriceWhereUniqueInput | Prisma.UserCheckPriceWhereUniqueInput[]
}

export type UserCheckPriceUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserCheckPriceCreateWithoutUserInput, Prisma.UserCheckPriceUncheckedCreateWithoutUserInput> | Prisma.UserCheckPriceCreateWithoutUserInput[] | Prisma.UserCheckPriceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserCheckPriceCreateOrConnectWithoutUserInput | Prisma.UserCheckPriceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserCheckPriceUpsertWithWhereUniqueWithoutUserInput | Prisma.UserCheckPriceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserCheckPriceCreateManyUserInputEnvelope
  set?: Prisma.UserCheckPriceWhereUniqueInput | Prisma.UserCheckPriceWhereUniqueInput[]
  disconnect?: Prisma.UserCheckPriceWhereUniqueInput | Prisma.UserCheckPriceWhereUniqueInput[]
  delete?: Prisma.UserCheckPriceWhereUniqueInput | Prisma.UserCheckPriceWhereUniqueInput[]
  connect?: Prisma.UserCheckPriceWhereUniqueInput | Prisma.UserCheckPriceWhereUniqueInput[]
  update?: Prisma.UserCheckPriceUpdateWithWhereUniqueWithoutUserInput | Prisma.UserCheckPriceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserCheckPriceUpdateManyWithWhereWithoutUserInput | Prisma.UserCheckPriceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserCheckPriceScalarWhereInput | Prisma.UserCheckPriceScalarWhereInput[]
}

export type UserCheckPriceUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserCheckPriceCreateWithoutUserInput, Prisma.UserCheckPriceUncheckedCreateWithoutUserInput> | Prisma.UserCheckPriceCreateWithoutUserInput[] | Prisma.UserCheckPriceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserCheckPriceCreateOrConnectWithoutUserInput | Prisma.UserCheckPriceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserCheckPriceUpsertWithWhereUniqueWithoutUserInput | Prisma.UserCheckPriceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserCheckPriceCreateManyUserInputEnvelope
  set?: Prisma.UserCheckPriceWhereUniqueInput | Prisma.UserCheckPriceWhereUniqueInput[]
  disconnect?: Prisma.UserCheckPriceWhereUniqueInput | Prisma.UserCheckPriceWhereUniqueInput[]
  delete?: Prisma.UserCheckPriceWhereUniqueInput | Prisma.UserCheckPriceWhereUniqueInput[]
  connect?: Prisma.UserCheckPriceWhereUniqueInput | Prisma.UserCheckPriceWhereUniqueInput[]
  update?: Prisma.UserCheckPriceUpdateWithWhereUniqueWithoutUserInput | Prisma.UserCheckPriceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserCheckPriceUpdateManyWithWhereWithoutUserInput | Prisma.UserCheckPriceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserCheckPriceScalarWhereInput | Prisma.UserCheckPriceScalarWhereInput[]
}

export type UserCheckPriceCreateWithoutUserInput = {
  module: $Enums.CheckModuleEnums
  price: number
}

export type UserCheckPriceUncheckedCreateWithoutUserInput = {
  module: $Enums.CheckModuleEnums
  price: number
}

export type UserCheckPriceCreateOrConnectWithoutUserInput = {
  where: Prisma.UserCheckPriceWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCheckPriceCreateWithoutUserInput, Prisma.UserCheckPriceUncheckedCreateWithoutUserInput>
}

export type UserCheckPriceCreateManyUserInputEnvelope = {
  data: Prisma.UserCheckPriceCreateManyUserInput | Prisma.UserCheckPriceCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserCheckPriceUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserCheckPriceWhereUniqueInput
  update: Prisma.XOR<Prisma.UserCheckPriceUpdateWithoutUserInput, Prisma.UserCheckPriceUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserCheckPriceCreateWithoutUserInput, Prisma.UserCheckPriceUncheckedCreateWithoutUserInput>
}

export type UserCheckPriceUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserCheckPriceWhereUniqueInput
  data: Prisma.XOR<Prisma.UserCheckPriceUpdateWithoutUserInput, Prisma.UserCheckPriceUncheckedUpdateWithoutUserInput>
}

export type UserCheckPriceUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserCheckPriceScalarWhereInput
  data: Prisma.XOR<Prisma.UserCheckPriceUpdateManyMutationInput, Prisma.UserCheckPriceUncheckedUpdateManyWithoutUserInput>
}

export type UserCheckPriceScalarWhereInput = {
  AND?: Prisma.UserCheckPriceScalarWhereInput | Prisma.UserCheckPriceScalarWhereInput[]
  OR?: Prisma.UserCheckPriceScalarWhereInput[]
  NOT?: Prisma.UserCheckPriceScalarWhereInput | Prisma.UserCheckPriceScalarWhereInput[]
  userId?: Prisma.StringFilter<"UserCheckPrice"> | string
  module?: Prisma.EnumCheckModuleEnumsFilter<"UserCheckPrice"> | $Enums.CheckModuleEnums
  price?: Prisma.IntFilter<"UserCheckPrice"> | number
}

export type UserCheckPriceCreateManyUserInput = {
  module: $Enums.CheckModuleEnums
  price: number
}

export type UserCheckPriceUpdateWithoutUserInput = {
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  price?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserCheckPriceUncheckedUpdateWithoutUserInput = {
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  price?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserCheckPriceUncheckedUpdateManyWithoutUserInput = {
  module?: Prisma.EnumCheckModuleEnumsFieldUpdateOperationsInput | $Enums.CheckModuleEnums
  price?: Prisma.IntFieldUpdateOperationsInput | number
}



export type UserCheckPriceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  module?: boolean
  price?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userCheckPrice"]>

export type UserCheckPriceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  module?: boolean
  price?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userCheckPrice"]>

export type UserCheckPriceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  module?: boolean
  price?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userCheckPrice"]>

export type UserCheckPriceSelectScalar = {
  userId?: boolean
  module?: boolean
  price?: boolean
}

export type UserCheckPriceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"userId" | "module" | "price", ExtArgs["result"]["userCheckPrice"]>
export type UserCheckPriceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserCheckPriceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserCheckPriceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserCheckPricePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserCheckPrice"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    userId: string
    module: $Enums.CheckModuleEnums
    price: number
  }, ExtArgs["result"]["userCheckPrice"]>
  composites: {}
}

export type UserCheckPriceGetPayload<S extends boolean | null | undefined | UserCheckPriceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserCheckPricePayload, S>

export type UserCheckPriceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserCheckPriceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCheckPriceCountAggregateInputType | true
  }

export interface UserCheckPriceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserCheckPrice'], meta: { name: 'UserCheckPrice' } }
  /**
   * Find zero or one UserCheckPrice that matches the filter.
   * @param {UserCheckPriceFindUniqueArgs} args - Arguments to find a UserCheckPrice
   * @example
   * // Get one UserCheckPrice
   * const userCheckPrice = await prisma.userCheckPrice.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserCheckPriceFindUniqueArgs>(args: Prisma.SelectSubset<T, UserCheckPriceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserCheckPriceClient<runtime.Types.Result.GetResult<Prisma.$UserCheckPricePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserCheckPrice that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserCheckPriceFindUniqueOrThrowArgs} args - Arguments to find a UserCheckPrice
   * @example
   * // Get one UserCheckPrice
   * const userCheckPrice = await prisma.userCheckPrice.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserCheckPriceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserCheckPriceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserCheckPriceClient<runtime.Types.Result.GetResult<Prisma.$UserCheckPricePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserCheckPrice that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCheckPriceFindFirstArgs} args - Arguments to find a UserCheckPrice
   * @example
   * // Get one UserCheckPrice
   * const userCheckPrice = await prisma.userCheckPrice.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserCheckPriceFindFirstArgs>(args?: Prisma.SelectSubset<T, UserCheckPriceFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserCheckPriceClient<runtime.Types.Result.GetResult<Prisma.$UserCheckPricePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserCheckPrice that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCheckPriceFindFirstOrThrowArgs} args - Arguments to find a UserCheckPrice
   * @example
   * // Get one UserCheckPrice
   * const userCheckPrice = await prisma.userCheckPrice.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserCheckPriceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserCheckPriceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserCheckPriceClient<runtime.Types.Result.GetResult<Prisma.$UserCheckPricePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserCheckPrices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCheckPriceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserCheckPrices
   * const userCheckPrices = await prisma.userCheckPrice.findMany()
   * 
   * // Get first 10 UserCheckPrices
   * const userCheckPrices = await prisma.userCheckPrice.findMany({ take: 10 })
   * 
   * // Only select the `userId`
   * const userCheckPriceWithUserIdOnly = await prisma.userCheckPrice.findMany({ select: { userId: true } })
   * 
   */
  findMany<T extends UserCheckPriceFindManyArgs>(args?: Prisma.SelectSubset<T, UserCheckPriceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserCheckPricePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserCheckPrice.
   * @param {UserCheckPriceCreateArgs} args - Arguments to create a UserCheckPrice.
   * @example
   * // Create one UserCheckPrice
   * const UserCheckPrice = await prisma.userCheckPrice.create({
   *   data: {
   *     // ... data to create a UserCheckPrice
   *   }
   * })
   * 
   */
  create<T extends UserCheckPriceCreateArgs>(args: Prisma.SelectSubset<T, UserCheckPriceCreateArgs<ExtArgs>>): Prisma.Prisma__UserCheckPriceClient<runtime.Types.Result.GetResult<Prisma.$UserCheckPricePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserCheckPrices.
   * @param {UserCheckPriceCreateManyArgs} args - Arguments to create many UserCheckPrices.
   * @example
   * // Create many UserCheckPrices
   * const userCheckPrice = await prisma.userCheckPrice.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCheckPriceCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCheckPriceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserCheckPrices and returns the data saved in the database.
   * @param {UserCheckPriceCreateManyAndReturnArgs} args - Arguments to create many UserCheckPrices.
   * @example
   * // Create many UserCheckPrices
   * const userCheckPrice = await prisma.userCheckPrice.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserCheckPrices and only return the `userId`
   * const userCheckPriceWithUserIdOnly = await prisma.userCheckPrice.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCheckPriceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCheckPriceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserCheckPricePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserCheckPrice.
   * @param {UserCheckPriceDeleteArgs} args - Arguments to delete one UserCheckPrice.
   * @example
   * // Delete one UserCheckPrice
   * const UserCheckPrice = await prisma.userCheckPrice.delete({
   *   where: {
   *     // ... filter to delete one UserCheckPrice
   *   }
   * })
   * 
   */
  delete<T extends UserCheckPriceDeleteArgs>(args: Prisma.SelectSubset<T, UserCheckPriceDeleteArgs<ExtArgs>>): Prisma.Prisma__UserCheckPriceClient<runtime.Types.Result.GetResult<Prisma.$UserCheckPricePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserCheckPrice.
   * @param {UserCheckPriceUpdateArgs} args - Arguments to update one UserCheckPrice.
   * @example
   * // Update one UserCheckPrice
   * const userCheckPrice = await prisma.userCheckPrice.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserCheckPriceUpdateArgs>(args: Prisma.SelectSubset<T, UserCheckPriceUpdateArgs<ExtArgs>>): Prisma.Prisma__UserCheckPriceClient<runtime.Types.Result.GetResult<Prisma.$UserCheckPricePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserCheckPrices.
   * @param {UserCheckPriceDeleteManyArgs} args - Arguments to filter UserCheckPrices to delete.
   * @example
   * // Delete a few UserCheckPrices
   * const { count } = await prisma.userCheckPrice.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserCheckPriceDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserCheckPriceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserCheckPrices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCheckPriceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserCheckPrices
   * const userCheckPrice = await prisma.userCheckPrice.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserCheckPriceUpdateManyArgs>(args: Prisma.SelectSubset<T, UserCheckPriceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserCheckPrices and returns the data updated in the database.
   * @param {UserCheckPriceUpdateManyAndReturnArgs} args - Arguments to update many UserCheckPrices.
   * @example
   * // Update many UserCheckPrices
   * const userCheckPrice = await prisma.userCheckPrice.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserCheckPrices and only return the `userId`
   * const userCheckPriceWithUserIdOnly = await prisma.userCheckPrice.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserCheckPriceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserCheckPriceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserCheckPricePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserCheckPrice.
   * @param {UserCheckPriceUpsertArgs} args - Arguments to update or create a UserCheckPrice.
   * @example
   * // Update or create a UserCheckPrice
   * const userCheckPrice = await prisma.userCheckPrice.upsert({
   *   create: {
   *     // ... data to create a UserCheckPrice
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserCheckPrice we want to update
   *   }
   * })
   */
  upsert<T extends UserCheckPriceUpsertArgs>(args: Prisma.SelectSubset<T, UserCheckPriceUpsertArgs<ExtArgs>>): Prisma.Prisma__UserCheckPriceClient<runtime.Types.Result.GetResult<Prisma.$UserCheckPricePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserCheckPrices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCheckPriceCountArgs} args - Arguments to filter UserCheckPrices to count.
   * @example
   * // Count the number of UserCheckPrices
   * const count = await prisma.userCheckPrice.count({
   *   where: {
   *     // ... the filter for the UserCheckPrices we want to count
   *   }
   * })
  **/
  count<T extends UserCheckPriceCountArgs>(
    args?: Prisma.Subset<T, UserCheckPriceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCheckPriceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserCheckPrice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCheckPriceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserCheckPriceAggregateArgs>(args: Prisma.Subset<T, UserCheckPriceAggregateArgs>): Prisma.PrismaPromise<GetUserCheckPriceAggregateType<T>>

  /**
   * Group by UserCheckPrice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCheckPriceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserCheckPriceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserCheckPriceGroupByArgs['orderBy'] }
      : { orderBy?: UserCheckPriceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserCheckPriceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserCheckPriceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserCheckPrice model
 */
readonly fields: UserCheckPriceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserCheckPrice.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserCheckPriceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserCheckPrice model
 */
export interface UserCheckPriceFieldRefs {
  readonly userId: Prisma.FieldRef<"UserCheckPrice", 'String'>
  readonly module: Prisma.FieldRef<"UserCheckPrice", 'CheckModuleEnums'>
  readonly price: Prisma.FieldRef<"UserCheckPrice", 'Int'>
}
    

// Custom InputTypes
/**
 * UserCheckPrice findUnique
 */
export type UserCheckPriceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCheckPrice
   */
  select?: Prisma.UserCheckPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCheckPrice
   */
  omit?: Prisma.UserCheckPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCheckPriceInclude<ExtArgs> | null
  /**
   * Filter, which UserCheckPrice to fetch.
   */
  where: Prisma.UserCheckPriceWhereUniqueInput
}

/**
 * UserCheckPrice findUniqueOrThrow
 */
export type UserCheckPriceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCheckPrice
   */
  select?: Prisma.UserCheckPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCheckPrice
   */
  omit?: Prisma.UserCheckPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCheckPriceInclude<ExtArgs> | null
  /**
   * Filter, which UserCheckPrice to fetch.
   */
  where: Prisma.UserCheckPriceWhereUniqueInput
}

/**
 * UserCheckPrice findFirst
 */
export type UserCheckPriceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCheckPrice
   */
  select?: Prisma.UserCheckPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCheckPrice
   */
  omit?: Prisma.UserCheckPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCheckPriceInclude<ExtArgs> | null
  /**
   * Filter, which UserCheckPrice to fetch.
   */
  where?: Prisma.UserCheckPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserCheckPrices to fetch.
   */
  orderBy?: Prisma.UserCheckPriceOrderByWithRelationInput | Prisma.UserCheckPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserCheckPrices.
   */
  cursor?: Prisma.UserCheckPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserCheckPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserCheckPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserCheckPrices.
   */
  distinct?: Prisma.UserCheckPriceScalarFieldEnum | Prisma.UserCheckPriceScalarFieldEnum[]
}

/**
 * UserCheckPrice findFirstOrThrow
 */
export type UserCheckPriceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCheckPrice
   */
  select?: Prisma.UserCheckPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCheckPrice
   */
  omit?: Prisma.UserCheckPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCheckPriceInclude<ExtArgs> | null
  /**
   * Filter, which UserCheckPrice to fetch.
   */
  where?: Prisma.UserCheckPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserCheckPrices to fetch.
   */
  orderBy?: Prisma.UserCheckPriceOrderByWithRelationInput | Prisma.UserCheckPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserCheckPrices.
   */
  cursor?: Prisma.UserCheckPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserCheckPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserCheckPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserCheckPrices.
   */
  distinct?: Prisma.UserCheckPriceScalarFieldEnum | Prisma.UserCheckPriceScalarFieldEnum[]
}

/**
 * UserCheckPrice findMany
 */
export type UserCheckPriceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCheckPrice
   */
  select?: Prisma.UserCheckPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCheckPrice
   */
  omit?: Prisma.UserCheckPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCheckPriceInclude<ExtArgs> | null
  /**
   * Filter, which UserCheckPrices to fetch.
   */
  where?: Prisma.UserCheckPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserCheckPrices to fetch.
   */
  orderBy?: Prisma.UserCheckPriceOrderByWithRelationInput | Prisma.UserCheckPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserCheckPrices.
   */
  cursor?: Prisma.UserCheckPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserCheckPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserCheckPrices.
   */
  skip?: number
  distinct?: Prisma.UserCheckPriceScalarFieldEnum | Prisma.UserCheckPriceScalarFieldEnum[]
}

/**
 * UserCheckPrice create
 */
export type UserCheckPriceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCheckPrice
   */
  select?: Prisma.UserCheckPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCheckPrice
   */
  omit?: Prisma.UserCheckPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCheckPriceInclude<ExtArgs> | null
  /**
   * The data needed to create a UserCheckPrice.
   */
  data: Prisma.XOR<Prisma.UserCheckPriceCreateInput, Prisma.UserCheckPriceUncheckedCreateInput>
}

/**
 * UserCheckPrice createMany
 */
export type UserCheckPriceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserCheckPrices.
   */
  data: Prisma.UserCheckPriceCreateManyInput | Prisma.UserCheckPriceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserCheckPrice createManyAndReturn
 */
export type UserCheckPriceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCheckPrice
   */
  select?: Prisma.UserCheckPriceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserCheckPrice
   */
  omit?: Prisma.UserCheckPriceOmit<ExtArgs> | null
  /**
   * The data used to create many UserCheckPrices.
   */
  data: Prisma.UserCheckPriceCreateManyInput | Prisma.UserCheckPriceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCheckPriceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserCheckPrice update
 */
export type UserCheckPriceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCheckPrice
   */
  select?: Prisma.UserCheckPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCheckPrice
   */
  omit?: Prisma.UserCheckPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCheckPriceInclude<ExtArgs> | null
  /**
   * The data needed to update a UserCheckPrice.
   */
  data: Prisma.XOR<Prisma.UserCheckPriceUpdateInput, Prisma.UserCheckPriceUncheckedUpdateInput>
  /**
   * Choose, which UserCheckPrice to update.
   */
  where: Prisma.UserCheckPriceWhereUniqueInput
}

/**
 * UserCheckPrice updateMany
 */
export type UserCheckPriceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserCheckPrices.
   */
  data: Prisma.XOR<Prisma.UserCheckPriceUpdateManyMutationInput, Prisma.UserCheckPriceUncheckedUpdateManyInput>
  /**
   * Filter which UserCheckPrices to update
   */
  where?: Prisma.UserCheckPriceWhereInput
  /**
   * Limit how many UserCheckPrices to update.
   */
  limit?: number
}

/**
 * UserCheckPrice updateManyAndReturn
 */
export type UserCheckPriceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCheckPrice
   */
  select?: Prisma.UserCheckPriceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserCheckPrice
   */
  omit?: Prisma.UserCheckPriceOmit<ExtArgs> | null
  /**
   * The data used to update UserCheckPrices.
   */
  data: Prisma.XOR<Prisma.UserCheckPriceUpdateManyMutationInput, Prisma.UserCheckPriceUncheckedUpdateManyInput>
  /**
   * Filter which UserCheckPrices to update
   */
  where?: Prisma.UserCheckPriceWhereInput
  /**
   * Limit how many UserCheckPrices to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCheckPriceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserCheckPrice upsert
 */
export type UserCheckPriceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCheckPrice
   */
  select?: Prisma.UserCheckPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCheckPrice
   */
  omit?: Prisma.UserCheckPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCheckPriceInclude<ExtArgs> | null
  /**
   * The filter to search for the UserCheckPrice to update in case it exists.
   */
  where: Prisma.UserCheckPriceWhereUniqueInput
  /**
   * In case the UserCheckPrice found by the `where` argument doesn't exist, create a new UserCheckPrice with this data.
   */
  create: Prisma.XOR<Prisma.UserCheckPriceCreateInput, Prisma.UserCheckPriceUncheckedCreateInput>
  /**
   * In case the UserCheckPrice was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserCheckPriceUpdateInput, Prisma.UserCheckPriceUncheckedUpdateInput>
}

/**
 * UserCheckPrice delete
 */
export type UserCheckPriceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCheckPrice
   */
  select?: Prisma.UserCheckPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCheckPrice
   */
  omit?: Prisma.UserCheckPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCheckPriceInclude<ExtArgs> | null
  /**
   * Filter which UserCheckPrice to delete.
   */
  where: Prisma.UserCheckPriceWhereUniqueInput
}

/**
 * UserCheckPrice deleteMany
 */
export type UserCheckPriceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserCheckPrices to delete
   */
  where?: Prisma.UserCheckPriceWhereInput
  /**
   * Limit how many UserCheckPrices to delete.
   */
  limit?: number
}

/**
 * UserCheckPrice without action
 */
export type UserCheckPriceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCheckPrice
   */
  select?: Prisma.UserCheckPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCheckPrice
   */
  omit?: Prisma.UserCheckPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCheckPriceInclude<ExtArgs> | null
}
