
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model CheckPrice
 * 
 */
export type CheckPrice = Prisma.CheckPriceModel
/**
 * Model Check
 * 
 */
export type Check = Prisma.CheckModel
/**
 * Model Report
 * 
 */
export type Report = Prisma.ReportModel
/**
 * Model BalanceTransaction
 * 
 */
export type BalanceTransaction = Prisma.BalanceTransactionModel
/**
 * Model Token
 * 
 */
export type Token = Prisma.TokenModel
